### ISSUE TITLE
How to get the steps used to build the Neo4j Graph?

### ISSUE THREAD

**Issue by steve-solun** [lyft/cartography#1014]
We are using cartography with different intels that help us to build our infra graph.
Please assist, how can I get all the relevant queries (all the CREATE, MERGE etc.) used to build my graph?
@achantavy @ramonpetgrave64

**Comment by achantavy** [comment]
Hi @steve-solun, what are you trying to do? Are you trying to get a list of every single query that was used to build your graph? If so, then neo4j enterprise allows you to turn on query logging which will log all queries, but you do have to pay for an enterprise license and it does get verbose and heavy. Not sure if this is what you're asking though.

**Comment by steve-solun** [comment]
I have found how to do it with the docs of Neo4j so we can close it.
