### ISSUE TITLE
Neo4j 5 support?

### ISSUE THREAD

**Issue by juju4** [lyft/cartography#1017]
**Feature request template**

*Title*: Neo4j 5 support?

*Description*:
Working fully, partially or better to avoid for now?
For new setup or existing one?
Recommendations?
Any quick way to test core cartography functions are fine?

* https://neo4j.com/release-notes/database/neo4j-5/
* https://neo4j.com/docs/upgrade-migration-guide/current/version-5/changelogs/configuration-settings/
* https://neo4j.com/docs/operations-manual/5/reference/configuration-settings/
* https://neo4j.com/docs/upgrade-migration-guide/current/version-5/migration/breaking-changes/

Top changes: requires JDK17+, backup and restore needed if migrating. index type update before migrating.

**Comment by achantavy** [comment]
Hey, thanks for filing an issue for this. The Neo4j 4.4 Python driver does not officially support Neo4j 5.x (https://neo4j.com/docs/api/python-driver/current/ says right now that supported versions are "4.4, 4.3, 3.5"), but you can probably point cartography against a Neo4j 5 database and see what happens - I'd be interested in hearing what you find. 

Based on the list of the driver's 4.4 to 5.x breaking changes (https://neo4j.com/docs/upgrade-migration-guide/current/version-5/migration/drivers/breaking-changes/) I don't think we have much to worry about here...

...however it seems that there are breaking cypher language changes: https://neo4j.com/docs/cypher-manual/5/deprecations-additions-removals-compatibility/

Sigh :).

**Comment by achantavy** [comment]
According to https://neo4j.com/developer/kb/neo4j-supported-versions/#_neo4j_database_enterprise_edition_4, Neo4j 4.4 will be supported at least until December 1, 2024.

@voutilad, @jexp - do you know if Neo4j 4.x will have minor version bumps, like will there be a 4.5, 4.6, or is 4.4 the final planned minor version for 4.x?

**Comment by voutilad** [comment]
> According to https://neo4j.com/developer/kb/neo4j-supported-versions/#_neo4j_database_enterprise_edition_4, Neo4j 4.4 will be supported at least until December 1, 2024.
> 
> @voutilad, @jexp - do you know if Neo4j 4.x will have minor version bumps, like will there be a 4.5, 4.6, or is 4.4 the final planned minor version for 4.x?

4.4 is the last of the 4.x series and the LTS version currently supported until 2025. There will not be a 4.5. See https://neo4j.com/developer/kb/neo4j-supported-versions/ for some details on the new versioning approach and LTS policy.
