### ISSUE TITLE
Drift detection CLI integration test fails occasionally

### ISSUE THREAD

**Issue by ecdavis** [lyft/cartography#104]
https://api.travis-ci.org/v3/job/559037067/log.txt

**Comment by achantavy** [comment]
@thomashli Was this resolved in #105 ?  (Not sure why the link to the PR didn't show up here even though you wrote this issue number in your commit message, oh well)

**Comment by thomashli** [comment]
I resolved the issue in 105 but I think I also got rid of/modified the test
for the new version of drift detection so it shouldn’t be a problem either
way.
