### ISSUE TITLE
EMRCluster node don't have firstseen property

### ISSUE THREAD

**Issue by VishalAgarW** [lyft/cartography#1064]
*Title*: EMRCluster node does not have firstseen property anymore

*Description*:
As part of https://github.com/lyft/cartography/pull/1038 change, EMRCluster node no longer has "firstseen" property. The problem is that "firstseen" is defined as explicit property in EMRClusterNodeProperties class 
firstseen: PropertyRef = PropertyRef('firstseen')

during query building phase, this ends up getting translated as:
 SET\n                i.lastupdated = $lastupdated,\ni.arn = item.ClusterArn,\ni.auto_terminate = item.AutoTerminate,\ni.autoscaling_role = item.AutoScalingRole,\ni.custom_ami_id = item.CustomAmiId,\n**i.firstseen = item.firstseen,**

however since the item doesn't have firstseen property, it gets reset to None and the original timestamp (set via ON CREATE SET) is lost.

*To Reproduce*:
1. Run cartography against an account that has EMR setup and then review the EMRCluster node.

**Comment by achantavy** [comment]
> however since the item doesn't have firstseen property, it gets reset to None and the original timestamp (set via ON CREATE SET) is lost.

D'oh. Thank you for the bug report! Fixing now.
