### ISSUE TITLE
Intel AWS ElasticSearch doesn't search all regions

### ISSUE THREAD

**Issue by hartnickaus** [lyft/cartography#1098]
**Bug Template**

*Title*: *Intel AWS ElasticSearch doesn't search all regions*

*Description*:
> When search of ElasticSearch for AWS is done, some regions are missed, but in particular ap-southeast-2

*To Reproduce*:
> Run script just for an aws account with just elasticsearch
AWS_PROFILE=xxxxxxxxxxxx /home/bitnami/.local/bin/cartography --neo4j-user neo4j --neo4j-password-env-var NEOPWD --neo4j-max-connection-lifetime 14400 --aws-requested-syncs "elasticsearch"

*Logs*:
> If applicable, copy and paste your console log

INFO:cartography.intel.aws.elasticsearch:Syncing Elasticsearch Service for region 'us-east-2' in account 'xxxxxxxxxxxx'.
INFO:cartography.intel.aws.elasticsearch:Syncing Elasticsearch Service for region 'us-east-1' in account 'xxxxxxxxxxxx'.
INFO:cartography.intel.aws.elasticsearch:Syncing Elasticsearch Service for region 'us-west-1' in account 'xxxxxxxxxxxx'.
INFO:cartography.intel.aws.elasticsearch:Syncing Elasticsearch Service for region 'us-west-2' in account 'xxxxxxxxxxxx'.
INFO:cartography.intel.aws.elasticsearch:Syncing Elasticsearch Service for region 'ap-northeast-1' in account 'xxxxxxxxxxxx'.
INFO:cartography.intel.aws.elasticsearch:Syncing Elasticsearch Service for region 'ap-northeast-2' in account 'xxxxxxxxxxxx'.
INFO:cartography.intel.aws.elasticsearch:Syncing Elasticsearch Service for region 'ap-south-1' in account 'xxxxxxxxxxxx'.
INFO:cartography.intel.aws.elasticsearch:Syncing Elasticsearch Service for region 'ap-southeast-1' in account 'xxxxxxxxxxxx'.
INFO:cartography.intel.aws.elasticsearch:Syncing Elasticsearch Service for region 'ca-central-1' in account 'xxxxxxxxxxxx'.
INFO:cartography.intel.aws.elasticsearch:Syncing Elasticsearch Service for region 'eu-central-1' in account 'xxxxxxxxxxxx'.
INFO:cartography.intel.aws.elasticsearch:Syncing Elasticsearch Service for region 'eu-west-1' in account 'xxxxxxxxxxxx'.
INFO:cartography.intel.aws.elasticsearch:Syncing Elasticsearch Service for region 'eu-west-2' in account 'xxxxxxxxxxxx'.
INFO:cartography.intel.aws.elasticsearch:Syncing Elasticsearch Service for region 'eu-west-3' in account 'xxxxxxxxxxxx'.
INFO:cartography.intel.aws.elasticsearch:Syncing Elasticsearch Service for region 'sa-east-1' in account 'xxxxxxxxxxxx'.
INFO:cartography.graph.statement:Completed aws_import_es_cleanup statement #1
INFO:cartography.graph.statement:Completed aws_import_es_cleanup statement #2
INFO:cartography.graph.job:Finished job aws_import_es_cleanup

*Please complete the following information:*:
>  - Cartography release version 0.72.1
>  - Python version: 3.9.2

**Comment by achantavy** [comment]
Thanks for the bug report. It looks like the elasticsearch sync is very old and used a hardcoded list of regions that did not include ap-southeast-2. PR incoming.
