### ISSUE TITLE
IAM statement not being transformed properly

### ISSUE THREAD

**Issue by VishalAgarW** [lyft/cartography#1102]
*Title*: IAM Statement is not being transformed properly

*Description*:
In  iam.py: _transform_policy_statements method if the original statement is not a list, it is transposed as a list:
    if not isinstance(statements, list):
        statements = [statements]

However the original dictionary value is not updated, in transform_policy_data:
statements = _transform_policy_statements(
                statements, policy_id,
            )

it should be:
policy_statement_map[policy_key] =  _transform_policy_statements(
                statements, policy_id,
            )

*To Reproduce*:
> inline policy statement value happens to be only this (note this is not a list but just a dict object) prior to transformation
{'Effect': 'Allow', 'Action': 'secretsmanager:GetSecretValue', 'Resource': 'arn:aws:secretsmanager:XXXXX:XXXXXXXX:secret:*'}

*Logs*:
 File "/var/cartography/cartography/intel/aws/iam.py", line 854, in load_policy_statements
statement_data_id=statement_data['id'],
 TypeError: string indices must be integers

**Comment by achantavy** [comment]
Wow, thank you for taking a close look and writing this detailed bug report. I am able to reproduce it with this unit test:

```python
def test_transform_policy_data():
    pol = {
        'some-arn': { 'pol-name': {
            'Effect': 'Allow',
            'Action': 'secretsmanager:GetSecretValue',
            'Resource': 'arn:aws:secretsmanager:XXXXX:XXXXXXXX㊙️*',
        }}
    }

    transform_policy_data(pol, 'inline')

    assert type(pol['some-arn']['pol-name']) == list
```

It fails with 

```
Expected :<class 'list'>
Actual   :<class 'dict'>
```

Will fix!
