### ISSUE TITLE
rds snapshot loading does not work properly

### ISSUE THREAD

**Issue by VishalAgarW** [lyft/cartography#1103]
*Title*: loading of RDS Snapshot does not use transformed value

*Description*:
> In rds.py: load_rds_snapshots, data is passed as the value of snapshots in neo4j_session.run

 snapshots = transform_rds_snapshots(data)

    neo4j_session.run(
        ingest_rds_snapshot,
        Snapshots=**data,**
        Region=region,
        AWS_ACCOUNT_ID=current_aws_account_id,
        aws_update_tag=aws_update_tag,
    )

It should be snapshots

**Comment by achantavy** [comment]
Thanks for the bug report!

Hi @spangenberg - can you take a look?
