### ISSUE TITLE
Unhandeled exception while fetching aws s3 objects

### ISSUE THREAD

**Issue by craigleander** [lyft/cartography#1115]
**Bug Template**

*Title*: *Un handeled exception while fetching aws s3 objects*

*Description*:
ERROR:cartography.graph.job:Unhandled error while executing statement in job 'AWS S3 Exposure Details': {code: Neo.ClientError.Statement.SyntaxError} {message: The property existence syntax `... exists(variable.property)` is no longer supported. Please use `variable.property IS NOT NULL` instead. (line 1, column 66 (offset: 65))
"MATCH (:AWSAccount{id: $AWS_ID})-[:RESOURCE]->(s:S3Bucket) WHERE EXISTS(s.anonymous_access)"
                                                                  ^}
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'

Traceback (most recent call last):
  File "/opt/homebrew/bin/cartography", line 8, in <module>

*To Reproduce*:
 cartography --neo4j-uri bolt://localhost:7687

*Screenshots*:
> If applicable, add screenshots to help explain your problem.

*Please complete the following information:*:
>  - Cartography release version: latest
>  - Python version: Python 3.10.9
>  - OS: Mac

**Comment by achantavy** [comment]
Hi, please use Neo4j 4.x.

It looks like you're using 5.x because the `EXISTS(..)` query that we use got deprecated in 5.x.

Also watch https://github.com/lyft/cartography/pull/1033 for our updates on Neo4j 5.x support.
