### ISSUE TITLE
Docker build fails due to dependancy issue

### ISSUE THREAD

**Issue by neilroebert** [lyft/cartography#1269]
**Description:**
Trying to build a docker image seems to be failing. It seems like the `pip install -r test-requirements.txt` command is causing urllib3 2.0.7 (at the time of opening this bug) to be installed, while the urllib3 version that is required by the rest of the dependancies need to be urllib3<1.27.0.

You can see in the logs that it downloads the correct version from the setup.py file, but then the `pip install -r test-requirements.txt` step then uninstalls that version and installs the latest version. I have confirmed that adding `urllib3<1.27.0` to `test-requirments.txt` fixes the issue. However this may not be a long term solution as we'd have to constantly manage this dependancy version.

This occurred on a fresh pull of the master branch (0.85.3).

**To Reproduce:**
Run the docker build command on the master branch. `docker build --no-cache --progress=plain -t lyft/cartography .`

**Logs:**
```
#11 56.67   Running setup.py develop for cartography
#11 57.15 Successfully installed PyJWT-2.8.0 PySocks-1.7.1 adal-1.2.7 applicationinsights-0.11.10 argcomplete-3.1.2 azure-cli-core-2.53.0 azure-cli-telemetry-1.1.0 azure-common-1.1.28 azure-core-1.29.4 azure-identity-1.14.1 azure-mgmt-compute-30.3.0 azure-mgmt-core-1.4.0 azure-mgmt-cosmosdb-9.3.0 azure-mgmt-resource-23.0.1 azure-mgmt-sql-1.0.0 azure-mgmt-storage-21.1.0 backoff-2.2.1 bcrypt-4.0.1 boto3-1.28.66 botocore-1.31.66 cachetools-5.3.1 cartography certifi-2023.7.22 cffi-1.16.0 charset-normalizer-3.3.0 circuitbreaker-1.4.0 crowdstrike-falconpy-1.3.2 cryptography-41.0.4 deprecation-2.1.0 distro-1.8.0 dnspython-2.4.2 duo-client-5.1.0 google-api-core-2.12.0 google-api-python-client-2.104.0 google-auth-2.23.3 google-auth-httplib2-0.1.1 googleapis-common-protos-1.61.0 httplib2-0.22.0 humanfriendly-10.0 idna-3.4 isodate-0.6.1 jmespath-1.0.1 jsonpickle-3.0.2 knack-0.11.0 kubernetes-28.1.0 marshmallow-3.20.1 msal-1.24.0b2 msal-extensions-1.0.0 msrest-0.7.1 msrestazure-0.6.4 neo4j-4.4.11 oauth2client-4.1.3 oauthlib-3.2.2 oci-2.113.0 okta-0.0.4 packaging-23.2 paramiko-3.3.1 pdpyras-5.1.2 pkginfo-1.9.6 policyuniverse-1.5.1.20230817 portalocker-2.8.2 protobuf-4.24.4 psutil-5.9.6 pyasn1-0.5.0 pyasn1-modules-0.3.0 pycparser-2.21 pygments-2.16.1 pynacl-1.5.0 pyopenssl-23.2.0 pyparsing-3.1.1 python-dateutil-2.8.2 python-digitalocean-1.17.0 pytz-2023.3.post1 pyyaml-6.0.1 requests-2.31.0 requests-oauthlib-1.3.1 rsa-4.9 s3transfer-0.7.0 six-1.16.0 statsd-4.0.1 tabulate-0.9.0 typing-extensions-4.8.0 uritemplate-4.1.1 urllib3-1.26.18 websocket-client-1.6.4 xmltodict-0.13.0
...
#11 59.90 Collecting urllib3>=2 (from types-requests->-r test-requirements.txt (line 8))
#11 59.93   Downloading urllib3-2.0.7-py3-none-any.whl.metadata (6.6 kB)
...
#11 61.54 Installing collected packages: types-PyYAML, distlib, urllib3, tomli, pluggy, platformdirs, nodeenv, iniconfig, identify, filelock, exceptiongroup, coverage, cfgv, virtualenv, types-requests, pytest, pytest-mock, pytest-cov, pre-commit
#11 61.61   Attempting uninstall: urllib3
#11 61.62     Found existing installation: urllib3 1.26.18
#11 61.62     Uninstalling urllib3-1.26.18:
#11 61.62       Successfully uninstalled urllib3-1.26.18
#11 62.22 ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
#11 62.22 botocore 1.31.66 requires urllib3<1.27,>=1.25.4; python_version < "3.10", but you have urllib3 2.0.7 which is incompatible.
#11 62.22 kubernetes 28.1.0 requires urllib3<2.0,>=1.24.2, but you have urllib3 2.0.7 which is incompatible
```

**Version info:**
> - Cartography tag 0.85.3
>  - Python version: Docker so not really applicable.

**Comment by achantavy** [comment]
Thanks for filing this issue.

What's weird is that I'm able to build the cartography container successfully and run the test suite (per these [instructions](https://lyft.github.io/cartography/dev/testing-with-docker.html#usage)), but when I try to run `cartography -h` in the container it fails with the dependency problem.

I haven't had time to do this yet but I would try fixing this by systematically removing items from [test-requirements.txt](https://github.com/lyft/cartography/blob/master/test-requirements.txt) until 
1. the container builds successfully
2. the unit and integration tests pass in the container
3. running the cartography CLI in the container does not throw any  dependency errors at runtime

If you're able to play with this and figure something out along these lines I'd be happy to merge in a PR.

**Comment by neilroebert** [comment]
Yeah exactly. Sorry my wording was a bit off. The container builds successfully. But I did notice the dependancy issues in the build logs. However, as you said it fails when running.

I've found that you can restrict urllib3 in the `test-requirements.txt` file. This clears out the issue. I'll see if the tests work with the lower version of urllib3 and then create the pr

**Comment by neilroebert** [comment]
@achantavy Can you please confirm something for me. Trying to run the tests according to the guide I get the following error with the pre-commit.

```
docker-compose run cartography make test                                                                            ✔  6s  cartography   12:32:54
[+] Building 0.0s (0/0)                                                                                                                                                                                  docker:desktop-linux
[+] Creating 1/0
 ✔ Container cartography-neo4j-1  Running                                                                                                                                                                                0.0s
[+] Building 0.0s (0/0)                                                                                                                                                                                  docker:desktop-linux
pre-commit run --all-files --show-diff-on-failure
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
Check the log at /home/cartography/.cache/pre-commit/pre-commit.log
make: *** [Makefile:4: test_lint] Error 1
```

So having a look at the logs `/home/cartography/.cache/pre-commit/pre-commit.log`:
```
...
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'rev-parse', '--show-cdup')
return code: 128
stdout: (none)
stderr:
    fatal: detected dubious ownership in repository at '/srv/cartography'
    To add an exception for this directory, call:
    
    	git config --global --add safe.directory /srv/cartography
...
```

It seems like the docker command `COPY --chown=cartography:cartography . /srv/cartography` is not doing what it's supposed to. But not sure if this is something on my side 🤷 ?

This is running off a fork done on master this morning. No file changes except for adding this line to `test-requirements.txt`:
```
urllib3<1.27
```

**Comment by achantavy** [comment]
Sorry ugh :\ I think I broke that, or I'm not sure if it ever worked in the first place. The pre-commit linter needs write permission to some path and so `make test_lint` can't run correctly. I'm getting weird inconsistent results with the Docker image with an M1 mac vs a Windows box running Ubuntu in WSL. It's really weird.

For now, only the `make test_integration` and `make test_unit` tasks work.

Definitely will accept help from someone who knows what they're doing with docker.

**Comment by achantavy** [comment]
For now as a workaround you can either

Option 1: try submit your PR and let the GitHub CI run the linter there and adjust accordingly. This is clunky because it's slow.

Option 2: Locally create a new Python virtual environment (I personally like using virtualenvwrapper), activate that, then run the linter:

```
cd /path/to/cartography
pip install -e .
pip install -r test-requirements.txt
make test_lint
```

You do not need to run Neo4j or install Java to run the linter. You just need a Python venv.

**Comment by achantavy** [comment]
Oh I see that you submitted https://github.com/lyft/cartography/pull/1270 -- thank you, will review there.
