### ISSUE TITLE
Handle missing networkIP while PROVISIONING

### ISSUE THREAD

**Issue by ramonpetgrave64** [lyft/cartography#129]
While an instance has `'status':'PROVISIONING'`, the field `nic['networkIP']` in the api response may not yet exist, so line 608 would result in a `KeyError`.

https://github.com/lyft/cartography/blob/1bb303c9f9ca125481852a68f3ea45608a93a804/cartography/intel/gcp/compute.py#L601-L608

Recommend changing to
 ```
NetworkIP=nic.get('networkIP'),
```

The [Instance Life Cycle](https://cloud.google.com/compute/docs/instances/instance-life-cycle) docs provide some information on state of an instance's resources at different instance statuses.

It could be good to also ingest `instance['status']` within `load_gcp_instances()`.

**Comment by achantavy** [comment]
Fixed in #131
