### ISSUE TITLE
Dockerfile --local can only be used inside a git repository

### ISSUE THREAD

**Issue by kmshar** [lyft/cartography#1347]
**Dockerfile --local can only be used inside a git repository**

*Description*:
>  Fails to build with default configuration.

*To Reproduce*:
> Build docker using `docker build -t lyft/cartography .`

*Logs*:

```
=> ERROR [10/10] RUN /usr/bin/git config --local user.name "cartography"                                                                                                         0.2s
------
 > [10/10] RUN /usr/bin/git config --local user.name "cartography":
0.203 fatal: --local can only be used inside a git repository
------
Dockerfile:33
--------------------
  31 |     # and the user that is going to run the unit&integ tests.
  32 |     RUN git config --global --add safe.directory /srv/cartography
  33 | >>> RUN /usr/bin/git config --local user.name "cartography"
  34 |
--------------------
ERROR: failed to solve: process "/bin/sh -c /usr/bin/git config --local user.name \"cartography\"" did not complete successfully: exit code: 128

```

*Screenshots*:

![cartography-docker-failed-build](https://github.com/user-attachments/assets/dbb31159-1d37-48b3-b50b-e348cf48cd5d)

**Comment by chandanchowdhury** [comment]
Looks like there is not a Git repo where you are running the command.

Did you use `git clone` or some other method?

Try `git init` and then build again using `dist.Dockerfile` to see if that helps.
