### ISSUE TITLE
DynamoDB import fails 

### ISSUE THREAD

**Issue by rburcham** [lyft/cartography#1350]
*Title*:
Multi-account aws import, on first account, dynamodb import crashes on first object found.

*Description*:
First time, multi-account import.  Working with the first aws account, cartograpy moves through accounts, groups, roles and s3, and each are imported into the graph.  Then still on the first aws account, it moves on to DynamoDB.   The account has one such object in us-east-2.  Cartography crashes trying to do the DynamoDB import.

*To Reproduce*:
This happens with any execution of ```cartography --neo4j-uri bolt://localhost:7687 --aws-sync-all-profiles```

*Logs*:
> ... snip ...
> INFO:cartography.intel.aws.dynamodb:Syncing DynamoDB for region in 'us-east-1' in account 'XXXXXXXXXXXX'.
> INFO:cartography.intel.aws.dynamodb:Loading Dynamo DB tables 0 for region 'us-east-1' into graph.
> INFO:cartography.intel.aws.dynamodb:Loading Dynamo DB GSI 0 for region 'us-east-1' into graph.
> INFO:cartography.intel.aws.dynamodb:Syncing DynamoDB for region in 'us-east-2' in account 'XXXXXXXXXXXX'.
> INFO:cartography.intel.aws.dynamodb:Loading Dynamo DB tables 1 for region 'us-east-2' into graph.
> ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
> Traceback (most recent call last):
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/sync.py", line 113, in run
>     stage_func(neo4j_session, config)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/util.py", line 197, in timed
>     return method(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/intel/aws/__init__.py", line 298, in start_aws_ingestion
>     sync_successful = _sync_multiple_accounts(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/intel/aws/__init__.py", line 169, in _sync_multiple_accounts
>     _sync_one_account(
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/intel/aws/__init__.py", line 64, in _sync_one_account
>     RESOURCE_FUNCTIONS[func_name](**sync_args)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/util.py", line 197, in timed
>     return method(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/intel/aws/dynamodb.py", line 119, in sync
>     sync_dynamodb_tables(
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/util.py", line 197, in timed
>     return method(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/intel/aws/dynamodb.py", line 109, in sync_dynamodb_tables
>     load_dynamodb_tables(neo4j_session, ddb_table_data, region, current_aws_account_id, aws_update_tag)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/util.py", line 197, in timed
>     return method(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/intel/aws/dynamodb.py", line 68, in load_dynamodb_tables
>     load(
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/client/core/tx.py", line 254, in load
>     load_graph_data(neo4j_session, ingestion_query, dict_list, **kwargs)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/client/core/tx.py", line 210, in load_graph_data
>     neo4j_session.write_transaction(
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/work/simple.py", line 443, in write_transaction
>     return self._run_transaction(WRITE_ACCESS, transaction_function, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/work/simple.py", line 336, in _run_transaction
>     result = transaction_function(tx, *args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/client/core/tx.py", line 191, in write_list_of_dicts_tx
>     tx.run(query, kwargs)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/work/transaction.py", line 143, in run
>     result._tx_ready_run(query, parameters)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/work/result.py", line 70, in _tx_ready_run
>     self._run(query, parameters, None, None, None, None)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/work/result.py", line 115, in _run
>     self._attach()
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/work/result.py", line 204, in _attach
>     self._connection.fetch_message()
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/io/_common.py", line 187, in inner
>     func(*args, **kwargs)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/io/_bolt4.py", line 314, in fetch_message
>     response.on_failure(summary_metadata or {})
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/io/_common.py", line 245, in on_failure
>     raise Neo4jError.hydrate(**metadata)
> neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: Query cannot conclude with CALL (must be RETURN or an update clause) (line 16, column 9 (offset: 528))
> "        CALL {"
>          ^}
> Traceback (most recent call last):
>   File "/usr/local/bin/cartography/bin/cartography", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/cli.py", line 768, in main
>     sys.exit(CLI(prog='cartography').main(argv))
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/cli.py", line 749, in main
>     return cartography.sync.run_with_config(self.sync, config)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/sync.py", line 191, in run_with_config
>     return sync.run(neo4j_driver, config)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/sync.py", line 113, in run
>     stage_func(neo4j_session, config)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/util.py", line 197, in timed
>     return method(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/intel/aws/__init__.py", line 298, in start_aws_ingestion
>     sync_successful = _sync_multiple_accounts(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/intel/aws/__init__.py", line 169, in _sync_multiple_accounts
>     _sync_one_account(
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/intel/aws/__init__.py", line 64, in _sync_one_account
>     RESOURCE_FUNCTIONS[func_name](**sync_args)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/util.py", line 197, in timed
>     return method(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/intel/aws/dynamodb.py", line 119, in sync
>     sync_dynamodb_tables(
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/util.py", line 197, in timed
>     return method(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/intel/aws/dynamodb.py", line 109, in sync_dynamodb_tables
>     load_dynamodb_tables(neo4j_session, ddb_table_data, region, current_aws_account_id, aws_update_tag)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/util.py", line 197, in timed
>     return method(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/intel/aws/dynamodb.py", line 68, in load_dynamodb_tables
>     load(
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/client/core/tx.py", line 254, in load
>     load_graph_data(neo4j_session, ingestion_query, dict_list, **kwargs)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/client/core/tx.py", line 210, in load_graph_data
>     neo4j_session.write_transaction(
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/work/simple.py", line 443, in write_transaction
>     return self._run_transaction(WRITE_ACCESS, transaction_function, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/work/simple.py", line 336, in _run_transaction
>     result = transaction_function(tx, *args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/cartography/client/core/tx.py", line 191, in write_list_of_dicts_tx
>     tx.run(query, kwargs)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/work/transaction.py", line 143, in run
>     result._tx_ready_run(query, parameters)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/work/result.py", line 70, in _tx_ready_run
>     self._run(query, parameters, None, None, None, None)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/work/result.py", line 115, in _run
>     self._attach()
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/work/result.py", line 204, in _attach
>     self._connection.fetch_message()
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/io/_common.py", line 187, in inner
>     func(*args, **kwargs)
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/io/_bolt4.py", line 314, in fetch_message
>     response.on_failure(summary_metadata or {})
>   File "/usr/local/bin/cartography/lib/python3.12/site-packages/neo4j/io/_common.py", line 245, in on_failure
>     raise Neo4jError.hydrate(**metadata)
> neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: Query cannot conclude with CALL (must be RETURN or an update clause) (line 16, column 9 (offset: 528))
> "        CALL {"
>          ^}

*Version information:*:
 - Cartography version:  0.93.0 (pip install)
 - Python version:  3.12.0
 - OS:  gentoo linux, kernel 6.10.6

**Comment by achantavy** [comment]
Hey, this looks weird. What version of Neo4j are you running? 

Neo4j versions 4 and 5 should accept this style of query (we test it here: https://github.com/lyft/cartography/blob/ad4d16a89d822423320a7918f47e620c538d698d/tests/unit/cartography/graph/test_querybuilder_complex.py#L21 and here https://github.com/lyft/cartography/tree/master/tests/integration/cartography/graph).

cartography will not work on neo4j 3.x (and 3.x is EOL'd too).

**Comment by rburcham** [comment]
I'm using neo4j-4.2.2

**Comment by achantavy** [comment]
@rburcham - Thank you very much for this report. I am able to reproduce this issue. The short answer is you need to use Neo4j 4.4. Older versions 4.2 and even 4.3 will fail. 

---

I started a neo4j-4.2.2-community container with 

```
docker run  --publish=7474:7474 --publish=7687:7687 -v data:/data   --env=NEO4J_AUTH=none --platform=linux/amd64 neo4j:4.2.2-community
```

and then I ran cartography's integration tests with

```
pytest -k test_load_dynamodb
```

and it fails:

![image](https://github.com/user-attachments/assets/0233d4d0-eaf6-4be7-a975-c514fc1af517)


I confirmed that this also fails with 4.3.


Then I ran the same test on 4.4 with

```
docker run  --publish=7474:7474 --publish=7687:7687    --env=NEO4J_AUTH=none --platform=linux/amd64 neo4j:4.4-community
```

and it works:

![image](https://github.com/user-attachments/assets/bf1fec76-ab66-47ce-9b3a-680048e474e4)


---

We will make sure to update the documentation to indicate that we only support 4.4 and above.

**Comment by achantavy** [comment]
I found the release note that we're relying on: https://github.com/neo4j/neo4j/wiki/Neo4j-4.4-changelog#cypher-31

> 4.4.0
> # Cypher
> Cypher now allows sub-queries ending in an update clause instead of a RETURN clause. These so-called unit sub-queries are called for their side-effects only and do not return values to the enclosing query.

**Comment by achantavy** [comment]
I've been pretty tied up this week -- if someone has a chance to update the neo4j requirements in our docs in a PR that'd be super appreciated

**Comment by achantavy** [comment]
Going to close this issue now that #1351 is merged

**Comment by rburcham** [comment]
I can confirm the import succeeds with neo4j-5.23.0
