### ISSUE TITLE
Dockerfile --local can only be used inside a git repository

### ISSUE THREAD

**Issue by hatchetation** [lyft/cartography#1363]
**Dockerfile --local can only be used inside a git repository**

This is a clone of closed issue #1347, opened by @kmshar . 

I believe the proximate cause may be the security-related change introduced in #1296 . 

*Description*:
> Fails to build with default configuration.

*To Reproduce*:
> 1. Update `Dockerfile` to use `ubuntu:jammy` to resolve an unrelated problem with `python3.10-dev` being unavailable in `ubuntu:focal`
> 2. Build docker using `docker build -t lyft/cartography .`

*Logs*:
```
 => [ 9/10] RUN git config --global --add safe.directory /srv/cartography                                                         0.1s
 => ERROR [10/10] RUN /usr/bin/git config --local user.name "cartography"                                                         0.1s
------
 > [10/10] RUN /usr/bin/git config --local user.name "cartography":
0.123 fatal: --local can only be used inside a git repository
------
Dockerfile:33
--------------------
  31 |     # and the user that is going to run the unit&integ tests.
  32 |     RUN git config --global --add safe.directory /srv/cartography
  33 | >>> RUN /usr/bin/git config --local user.name "cartography"
  34 |
--------------------
ERROR: failed to solve: process "/bin/sh -c /usr/bin/git config --local user.name \"cartography\"" did not complete successfully: exit code: 128
```

>  - Cartography commit hash 2420ef65a1327025931edaa20a26a58f53651e55
>  - Python version: [3.10]
>  - OS: Docker on MacOS

**Comment by chandanchowdhury** [comment]
Background: https://github.com/lyft/cartography/blob/master/.github/workflows/publish-to-ghcr.yml#L47

@achantavy I do not know the history, so need your input on if we should replace https://github.com/lyft/cartography/blob/master/Dockerfile with https://github.com/lyft/cartography/blob/master/dist.Dockerfile ?

**Comment by achantavy** [comment]
Hey @hatchetation some clarifying questions - are you trying to spin up cartography in production or is this for playing around on a test machine?

For my own cartography testing I don't use docker, I create venvs and `pip install` things to it, so tbh I'm unfamiliar with how Docker is normally used in OSS Python projects or what are the expected ergonomics/scenarios/outcomes, but I do want to make this as smooth as possible - let me know as many details as you can.

If it's easier I have a thread on slack here: https://lyftoss.slack.com/archives/CTZUQL0KX/p1727375916891719, either way works.

**Comment by hatchetation** [comment]
@chandanchowdhury Thanks, that got me a lot further. 

I'm trying to spin it up locally on an MacOS workstation for initial testing. I was following the directions for [Testing with docker](https://lyft.github.io/cartography/dev/testing-with-docker.html) from the wiki. 

I can totally give pip+venv+standlaone neo4j a shot - was just trying Docker first due to seeing this: 

> Cartography should work on both Linux and Windows, but bear in mind we’ve only tested it on Linux so far.

**Comment by achantavy** [comment]
@hatchetation -  Ah got it. That instruction is intended for dev flow, I'll see if I can make that more obvious. 

For local initial testing just to get it running, this doc is better: https://lyft.github.io/cartography/install.html. This involves pip + venv + Dockered neo4j, because installing neo4j and a JRE can be a lot.

---

I'd love to hear what you think works best for an initial setup: `dockered cartography + dockered neo4j` - or - `pip + venv + dockered neo4j`.
