### ISSUE TITLE
Attack modeling with Cartography

### ISSUE THREAD

**Issue by scriptsrc** [lyft/cartography#140]
Hey all,

I was thinking about the CapitalOne breach.  They had an instance that was vulnerable to SSRF and internet accessible. The instance was running with an IAM Role that had access to the S3 bucket containing the customer PII that was leaked.

I was hoping I could model this attack in Cartography. It's only slightly more complicated than the typical "bucket left open to the world".

I was hoping that I could build a query that would help me find the shortest routes from internet accessible infrastructure `(ec2:EC2Instance{exposed_internet: true})` to an IAM Role that had access to a given S3 bucket.

Unfortunately, neither `EC2Instance`, nor `AutoScalingGroup` have any mapping to either `InstanceProfile` or `IAM Roles`, and `LaunchConfig` doesn't seem to exist either.

Further, there's not currently a mapping of `S3Bucket` to IAMRole either. (I understand this would be difficult, even with PolicyUniverse's `whos_allowed()`

```
policy = Policy(policy05)
assert policy.whos_allowed() == set([
    PrincipalTuple(category='principal', value='arn:aws:iam::*:role/Hello'),
    PrincipalTuple(category='principal', value='arn:aws:iam::012345678910:root'),
    ConditionTuple(category='cidr', value='0.0.0.0/0'),
    ConditionTuple(category='account', value='012345678910')
])
```

Is this kind of attack modeling the idea behind Cartography? Is the end goal to be able to build these kind of queries? I can see a future where we're mapping the shortest (weakest) routes from our sensitive data through AWS to our internet exposed infrastructure, and then mapping the inspector findings on those AMI's to find the most likely routes an attacker may take. That's the power of the graphdb, right?

Is Lyft running any cool complex queries beyond what's in the documentation?  If so, I'd friggin *love* to read about them.  Thank you.

**Comment by achantavy** [comment]
This is one of our favorite questions and I'm so glad you asked about it :-). 

Here's a quick, fun starting point:
```
MATCH (a1:AWSAccount)-[:AWS_ROLE]->(r1:AWSRole)-[:STS_ASSUMEROLE_ALLOW]->(r2:AWSRole)<-[:AWS_ROLE]-(a2:AWSAccount) WHERE a1 <> a2 RETURN * limit 100
```

This shows opportunities to move between different AWS accounts by assuming IAM roles.

**Comment by scriptsrc** [comment]
Very cool @achantavy

**Comment by scriptsrc** [comment]
I'll close this ticket now, but I'm very interested in building out these kind of capabilities.

Thank you so much for this tool.
