### ISSUE TITLE
Feature request: ingest Google Cloud Storage buckets

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#141]
Would like to ingest [Google Cloud Storage](https://cloud.google.com/storage/) [buckets](https://googleapis.github.io/google-cloud-python/latest/storage/client.html#google.cloud.storage.client.Client.list_buckets) with Cartography.

If anyone has cycles to work on this, contributions are definitely super welcome :-)

**Comment by manesioz** [comment]
@achantavy  I'd like to look into this if no one else is. I'm assuming we would want similar functionality that we currently have for AWS [s3](https://github.com/lyft/cartography/blob/master/cartography/intel/aws/s3.py)? Anything I should be aware of?

**Comment by achantavy** [comment]
@manesioz Thanks for offering to help!  I think a first PR should focus on just retrieving the buckets and connecting them to GCP projects.  Here's some pointers on getting started:

Getting the objects appears to be fairly straightforward.  You first instantiate a storage client like this:
```
storage = googleapiclient.discovery.build('storage', 'v1', credentials=credentials)
```

and then you can call list buckets on a project like this:
```
req = storage.buckets().list(project='some-project-name')
res = req.execute()
```

Then `pprint(res)` ends up looking like this:
```
{'items': [{'etag': 'etag',
            'iamConfiguration': {'bucketPolicyOnly': {'enabled': False},
                                 'uniformBucketLevelAccess': {'enabled': False}},
            'id': 'bucket-id',
            'kind': 'storage#bucket',
            'location': 'US-EAST4',
            'locationType': 'region',
            'metageneration': '1',
            'name': 'bucket-id',
            'projectNumber': '1234',
            'selfLink': 'https://www.googleapis.com/storage/v1/b/bucket-id',
            'storageClass': 'REGIONAL',
            'timeCreated': '2019-02-20T22:17:17.899Z',
            'updated': '2019-02-20T22:17:17.899Z'}],
 'kind': 'storage#buckets'}
```

The easiest way to attack this task would be to copy the patterns from our existing GCP code.  For example:
- Using resource providers: https://github.com/lyft/cartography/blob/master/cartography/intel/gcp/__init__.py#L48
- Using the get + transform + load + cleanup pattern: I would recommend copying VPC ingestion here because it attaches VPCs to projects: https://github.com/lyft/cartography/blob/master/cartography/intel/gcp/compute.py#L873

We'll definitely welcome a rough work-in-progress and be willing to work with you on improving it.

**Comment by manesioz** [comment]
@achantavy Thank you so much for such a detailed response, I really appreciate it! I'll start on this as soon as possible.

**Comment by achantavy** [comment]
Oh yeah, and it probably makes most sense to have these new functions in a new file cartography/intel/gcp/storage.py

Look forward to hearing from you!
