### ISSUE TITLE
Add profile & platform argument in cartography cli

### ISSUE THREAD

**Issue by quark2hub** [lyft/cartography#150]
Hi Team,

1) Request to add **--profile <aws-account-name/aws-account-number>** attribute in cartography cli so that individual account could be identified and bifurcated on Neo4j console.

Eg; cartograph was executed for 2 different AWS account via separate teams. But both of them merged the sync data in single "default" profile in Neo4j.

Team A:
INFO:cartography.intel.aws:Syncing AWS account with ID 'AAAA' using configured profile 'default'.

Team B:
INFO:cartography.intel.aws:Syncing AWS account with ID 'BBBB' using configured profile 'default'.

2) Request to add **--platform <aws/gcp>** attribute in cartography cli so that cartograph should not be running unnecessary steps/cycle. 

Thank You.

**Comment by ecdavis** [comment]
1 -- the profile name is not added to the neo4j DB at all, it's logged primarily for debugging purposes (to determine which AWS creds were used to sync a particular account). The use case you described here should work as-is. Have you seen bugs or unexpected behavior when doing this?

2 -- our recommendation in this case is to create a custom sync script and call that. We don't have any docs on how to do this right now. This is an area we definitely need to improve, especially as we add more intel modules.

**Comment by quark2hub** [comment]
Thank You @ecdavis for the reply.

1 -- No, issue/bug observed.

2 -- Sure, Thank You.
