### ISSUE TITLE
Cypher Favorites Management

### ISSUE THREAD

**Issue by marco-lancini** [lyft/cartography#177]
Hi!
First of all, thank you for your work on Cartography!

I was wondering if you have any suggestions on how to handle favorite Cypher queries, especially how to save and share them among different users. 

The neo4j documentation recommends to manually dump them via the console in a browser's developer tools ([source](https://neo4j.com/developer/kb/how-do-i-export-cypher-favorites-recorded-in-the-browser/)), but I was wondering if there is a more efficient (and automated) way that you use at Lyft (and that you can share with the public)

**Comment by achantavy** [comment]
Hey there,
Browser local storage is basically the only "automated" way to store queries, and as you've found, there isn't really a great way out of the box to share queries with others.  There are other solutions that build on top of Neo4j to give that feature, but these licenses can be pricey.

At Lyft we consume the data in different internal dashboards and have things like Slackbots to abstract away some of the complexity of a cypher query for users -- this is a great topic for a future blog post but we've been swamped haha.  Basically these solutions use the Neo4j python driver to connect to our running instance and run queries -- nothing super fancy or clever there.

Another way of consuming data could be to make shell scripts to make *.csv files on queries you're interested in - this is usually very helpful for people needing to generate asset inventories.  For example, if you want to perform the very enterprise-y task of generating a *csv inventory for all EC2 instances grouped up by AWS account,

Run`brew install jq` (on a Mac) and then run:

```
curl -s -H 'Content-Type: application/json'  -d '{ "statements" : [ { "statement" : "MATCH (acc:AWSAccount)-[r2]-(asg:AutoScalingGroup)-[r:MEMBER_AUTO_SCALE_GROUP]-(e:EC2Instance) return acc.id as aws_account_id, acc.name as aws_account_name, asg.arn as asg_arn, asg.name as asg_name, \"arn:aws:ec2:\" + e.region + \":\" + acc.id + \":instance/\" + e.instanceid as ec2_instance_arn, e.instanceid as ec2_instance_id, e.launchtime as launchtime, e.publicdnsname as publicdnsname, e.instancetype as instancetype, e.state as instance_state, e.region as region order by aws_account_name, asg_name, ec2_instance_id" } ] }'   http://yourneo4j:7474/db/data/transaction/commit \| jq -r '(.results[0]) \| .columns,.data[].row \| @csv' > instances-`date "+%m-%d-%Y-%H%M"`.csv
```

Anyway, this probably doesn't get at what you're looking for but I hope this gives some insight on how to consume results out of Neo4j.  We've got a long backlog on things we want to do to better socialize the graph, so thanks for the question!

**Comment by marco-lancini** [comment]
Hi @achantavy, thank you for your reply!

This is indeed very useful.
We would love to hear more about your experiences with 3rd party integrations (e.g., Github, Envoy, Jira) as well as data enrichment, and if these topics are part of the Cartography's roadmap.
