### ISSUE TITLE
Change neo4j query templating to use string.Template

### ISSUE THREAD

**Issue by ecdavis** [lyft/cartography#179]
See https://github.com/lyft/cartography/pull/174/files

**Comment by tobli** [comment]
I'm assuming this refers to when #VARIABLE_NAME# is used with String.replace to create dynamic Cypher statements, not for variables in "regular" Cypher statements.

i.e.
https://github.com/lyft/cartography/blob/1a440cf42ba6f88fc079608d83b84921222ca220/cartography/intel/aws/ec2.py#L391
https://github.com/lyft/cartography/blob/1a440cf42ba6f88fc079608d83b84921222ca220/cartography/intel/aws/ec2.py#L882-L884

**Comment by achantavy** [comment]
Closing this issue; the codebase is thankfully clean now from this bad pattern :P  Will reopen if it ends up that I have missed something.
