### ISSUE TITLE
[Feature Request] Integration with GKE/EKS

### ISSUE THREAD

**Issue by marco-lancini** [lyft/cartography#214]
Hello! Do you have any plan regarding the ingestion of data from GKE/EKS?

**Comment by achantavy** [comment]
Thanks for the suggestion!  We want visibility on k8s too but can't make any commitments at the moment.  As always, we welcome PRs and discussion.

**Comment by marco-lancini** [comment]
* EKS has been integrated in PR #266 and #269.
* GKE will be next

**Comment by marco-lancini** [comment]
* GKE has been integrated in PR #271
