### ISSUE TITLE
GCP: Incorrect Ingestion for projects without organizations

### ISSUE THREAD

**Issue by ramonpetgrave64** [lyft/cartography#217]
https://cloud.google.com/resource-manager/reference/rest/v1/projects#Project
From the gcp project items in `projects.list` method response, the `project.parent` attribute is optional, and isn't set for projects that are not under folders, projects, or organizations.

I can't verify more details now, but I think the query on line 172 fails if the `parentid` variable is unset.
https://github.com/lyft/cartography/blob/95e8e11913e2a44a4d4682506d8364a638ceac69/cartography/intel/gcp/crm.py#L138-L173

I think it might even be putting parentless projects into incorrect organizations or folders, because of variable scope. 

I'd been using this little snippet here to deal with that. 
```
for project in data:
        if project.get('parent', None):
            if project['parent']['type'] == "organization":
                query = """
                MERGE (parent:GCPOrganization{id:{ParentId}})
                ON CREATE SET parent.firstseen = timestamp()
                """
                parentid = f"organizations/{project['parent']['id']}"
            elif project['parent']['type'] == "folder":
                query = """
                MERGE (parent:GCPFolder{id:{ParentId}})
                ON CREATE SET parent.firstseen = timestamp()
                """
                parentid = f"folders/{project['parent']['id']}"
        # attempt to put into an empty org
        else:
            query = """
            MERGE (parent:GCPOrganization{id:{ParentId}})
            ON CREATE SET parent.firstseen = timestamp()
            """
            parentid = "organizations/EMPTYORG"
        query += """
        MERGE (project:GCPProject{id:{ProjectId}})
        ...
```

**Comment by achantavy** [comment]
Got it, thanks for the detailed explanation.  Yeah, if a given project does not have `parent` set, then it looks like the query will fail.  Any chance you can share redacted project data from the projects API call that doesn't have `parent` specified?

**Comment by achantavy** [comment]
Bit more context: I'll use the data to make an integration test

**Comment by ramonpetgrave64** [comment]
Using the [API Explorer](https://cloud.google.com/resource-manager/reference/rest/v1/projects/list), here's what my `projects.list` response looks like. This is all I can show you, since, as a free user, I cannot create folders or organizations.

```
{
  "projects": [
    {
      "projectNumber": "123456789012",
      "projectId": "myproject-987654",
      "lifecycleState": "ACTIVE",
      "name": "myproject",
      "createTime": "2019-11-11T21:06:32.043Z"
    }
  ]
}
```

**Comment by achantavy** [comment]
Thanks!
