### ISSUE TITLE
Ingest GitHub data 

### ISSUE THREAD

**Issue by tayasteere** [lyft/cartography#228]
*Title*: Ingest GitHub repo data

*Description*:
Ingest GitHub repo info to enable exploration of user access to code. This is currently a Lyft internal module.

**Comment by nealharris** [comment]
It seems like this could enable more than just understanding user access to code. For example, suppose GitHub detects a vulnerable dependency in a manifest file for some app. GitHub can tell you when that vulnerability has been patched in your source control, but won't tell you whether that fix has been deployed everywhere.

Maybe that's scope creep for this issue? Anyway, I've always thought it'd be cool to connect vulnerable dependency data with a tool that understands where that code is deployed.

**Comment by achantavy** [comment]
@nealharris This is exactly the way that we use this data internally :).  In the past we wrote these functions without thinking about OSS but now we're writing as much as we can in open-source-land first.  Definitely welcome help here too if there's a particular app you have in mind!
