### ISSUE TITLE
Reorganize documentation so that available modules are more easily visible

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#230]
*Title*: *Reorganize documentation so that available modules are more easily visible*

*Description*:
> Describe your idea.  Please be detailed.  If a feature request, please
describe the desired behavior, what scenario it enables, and how it
would be used.

Our current (very thorough and beautiful 😁) readme has become very long and could benefit from being split up into different sections.  It could help others better discover our tool if we made it easier to see at a glance what data Cartography pulls.

We can discuss this in more detail below but ideally we would have configuration and installation in `docs/setup/` or something and all the other sections in their own folders under `docs/`.

**Comment by marco-lancini** [comment]
I like the idea of having more structured documentation.
For new people just approaching Cartography (trying to remember when I first started) I'd say it would be useful to have a clear separation between:

1. configuration of cloud providers
2. configuration of cartography itself
3. what modules are available and what data is going to be collected
4. dev documentation (how to create new modules, how to script which intel modules to use, etc.)

As a plus, have you considered providing a Docker image for easy deployment on k8s?
I'm happy to help with it if needed

**Comment by achantavy** [comment]
I think that structure makes sense.

When it comes to containers, we've been hesitant to provide direction for [these reasons](https://github.com/lyft/cartography/issues/159), but I think we'd be open to providing examples for the community to quickly and easily get started - maybe something like what Envoy does here: https://github.com/envoyproxy/envoy/tree/master/examples.

Admittedly I don't know much about containers but any help here is greatly appreciated.

**Comment by marco-lancini** [comment]
What would you think of a setup similar to the one outlined in the following blog post? (section "Deployment on Kubernetes")
* https://www.marcolancini.it/2020/blog-mapping-moving-clouds-with-cartography/#deployment-on-kubernetes

**Comment by achantavy** [comment]
@marco-lancini I would love that, I think a section on possible deployment options could be helpful.  The section wouldn't be prescriptive, but it would provide helpful examples on how to use it in prod.  We could link to your blog post, and we could also take elements of it and adapt it here.  I'll create a follow-up issue to do this.
