### ISSUE TITLE
Support for AWS_PROFILE environment variable

### ISSUE THREAD

**Issue by marizmendi** [lyft/cartography#233]
*Title*: *Support for AWS_PROFILE environment variable*

*Description*:
It would be very helpful to support the `AWS_PROFILE` environment variable and not use only the default profile if the env variable is set.
This enables users with more than one aws profile setup to choose which one they want to run cartography against without having to tamper with the `~/.aws/credentials` file to set their desired account as the default. 

This could also be achieved by adding a `--profile` option but having `AWS_PROFILE` would make the command leaner.

**Comment by achantavy** [comment]
Hi @marizmendi, sorry for the late reply.  I'll have to dig a bit but if I recall correctly we run a setup internally that avoids use of the `credentials` file.  I'll figure this out and reply back if there's an easy way to show how to do this without a Cartography code change.

**Comment by achantavy** [comment]
CC: @SecPrez

**Comment by achantavy** [comment]
Hi @marizmendi, this is finally getting fixed in #272; big thanks to @rsclarke-vgw.

**Comment by achantavy** [comment]
This has been fixed.
