### ISSUE TITLE
AWS: Cartography should mark uploaded and duplicate EC2 Key PAirs

### ISSUE THREAD

**Issue by ramonpetgrave64** [lyft/cartography#240]
**Feature request template**

*Title*: *Track uploaded and duplicate EC2 Key Pairs*

*Description*:
AWS allows you to upload a public key to create an EC2 Key Pair. Two Key Pairs uploaded with the same public key will have matching fingerprints in AWS. Cartography should be able to mark EC2KeyPair nodes as duplicates, and add relationships between them.

For uploaded Key Pairs, AWS will generate 32 digit MD5 fingerprints, while AWS-generated Key Pairs will have 40 digit SHA-1 fingerprints. Cartography should be able to mark EC2KeyPair nodes as user-uploaded.

[*Relevant Links*:]
[EC2 Key Pairs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html#verify-key-pair-fingerprints)

**Comment by achantavy** [comment]
Hey @ramonpetgrave64, just so I understand, what is the scenario you see for marking duplicate keypairs?  Is it something like wanting to identify cases of credential reuse?

As for user-uploaded keypairs, what is the reason for calling them out other than the fingerprint size difference?

**Comment by ramonpetgrave64** [comment]
Yes, it's basically for spotting credential reuse.

> Hey @ramonpetgrave64, just so I understand, what is the scenario you see for marking duplicate keypairs? Is it something like wanting to identify cases of credential reuse?

Yes, this is basically for spotting credential reuse.

> As for user-uploaded keypairs, what is the reason for calling them out other than the fingerprint size difference?

No other reason than having info on the origin of a keypair, i.e., whether it was generated by AWS or not.
