### ISSUE TITLE
Okta API Key error after removing Sync

### ISSUE THREAD

**Issue by And03380** [lyft/cartography#242]
**Feature request template**

Title: Okta API key error after removing sync 

After removing the Okta sync (commenting out from sync.py) I am still getting the following error:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/cartography", line 7, in <module>
    from cartography.cli import main
  File "/home/ubuntu/.local/lib/python3.5/site-packages/cartography/cli.py", line 191
    logger.debug(f"Reading API key for Okta from environment variable {config.okta_api_key_env_var}")

Tried removing entire /intel/okta/__init__ and still received the same error.
                                                                                                   ^
Thank you,
AA

**Comment by achantavy** [comment]
Hi, which commit hash/release version of Cartography are you running?

What are the precise steps to reproduce the issue?  What did you run on the command-line?

Thanks!

**Comment by And03380** [comment]
Hi Alex,

I appreciate the help!

Here is my commit hash: commit 8186273b9d7ad97537c16545de9bd7a0f9d04b01

In the command line I ran:  *cartography --neo4j-uri
bolt://ec2-XX-XX-XX-XXX.compute-1.amazonaws.com:7687
<http://ec2-XX-XX-XX-XXX.compute-1.amazonaws.com:7687>*

Thanks,
Austin

**Comment by kunaals** [comment]
Hi AA,

I appreciate your patience! I tried reproducing your issue but didn't have any luck. It seems strange that an error message would come up regarding the logger message given that the [if statement at cli.py#190](https://github.com/lyft/cartography/blob/b2f4fd2b360c2e93f61cb3e4bc0c443e33cefe4d/cartography/cli.py#L190) evaluated to true. To help us debug further, could you try printing out the values of `config.okta_org_id` and `config.okta_api_key_env_var` **inside the if statement?**

As a temporary fix, you could try setting both of the above variables to `None` directly before the if statement on line 190. That should fix your problem at least temporarily.

```
# Okta config
config.okta_org_id = None
config.okta_api_key_env_var = None
if config.okta_org_id and config.okta_api_key_env_var:
    logger.debug(f"Reading API key for Okta from environment variable {config.okta_api_key_env_var}")
    config.okta_api_key = os.environ.get(config.okta_api_key_env_var)
```

Best,
Kunaal
