### ISSUE TITLE
Add more sample queries to docs

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#249]
*Title*: *Add more sample queries to docs*

*Description*:
> Describe your idea.  Please be detailed.  If a feature request, please
describe the desired behavior, what scenario it enables, and how it
would be used.

Would like to add more sample queries to docs/usage/samplequeries.md.

For example:
- Which instances have ssh's port 22 as inbound whitelisted from a single ip address?

- Which EC2 Key Pairs are duplicates and user-uploaded?

- And perhaps some IAM related queries.

I am opening this issue to capture more ideas for sample queries that we should include.  Please reply with your ideas.

**Comment by marco-lancini** [comment]
That's definitely a good idea. When I first started with Cartography I spent some time to go through the schema (almost) line-by-line to create the most meaningful queries for the data we have.
The result is in the `queries.json` file I shared here: https://github.com/marco-lancini/cartography-queries.
The file contains additional metadata that we use for programmatic filtering/usage, by the Cypher queries can be reused easily, and even embedded in the docs if you like!
