### ISSUE TITLE
Include (or link to) deployment examples in Cartography documentation

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#250]
**Feature request template**

*Title*: *Include (or link to) deployment examples in Cartography documentation*

*Description*:
> Describe your idea.  Please be detailed.  If a feature request, please
describe the desired behavior, what scenario it enables, and how it
would be used.

See discussion at https://github.com/lyft/cartography/issues/230#issuecomment-586897785

We want to be clear in these docs that these are not the only ways to deploy it, and we also want to provide useful examples.  @marco-lancini's [blog post](https://www.marcolancini.it/2020/blog-mapping-moving-clouds-with-cartography/#deployment-on-kubernetes) could be a good starting point.

**Comment by marco-lancini** [comment]
Hi @achantavy, as I was mentioning: if needed, I'm also happy to extract the Kubernetes deployment itself from the blog post and add some examples to the Cartography repo

**Comment by achantavy** [comment]
@marco-lancini Awesome!

I was thinking we could make a `docs/setup/deployment` folder and put a `kubernetes.md` in there, and then we'd adapt `docs/setup/install.md` to link to it.

**Comment by marco-lancini** [comment]
No `stale` bot, this is not stale :D
