### ISSUE TITLE
As a prospective Cartography user, I'd like to play with sample data and query examples without needing to install Neo4j

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#251]
**Feature request template**

*Title*: *As a prospective Cartography user, I'd like to play with sample data and query examples without needing to install Neo4j*

*Description*:
> Describe your idea.  Please be detailed.  If a feature request, please
describe the desired behavior, what scenario it enables, and how it
would be used.

One way of doing this could be to provide a container with sample data (basically the output of a `get_*` function in one of our intel modules) and then on container startup, load that sample data to the Neo4j living in that container.

I'd like to see what others think of this idea or if there's a better way of accomplishing this task.

**Comment by ramonpetgrave64** [comment]
I think the easiest thing might be to use Neo4j's export and import functions with the Neo4j Playground.
