### ISSUE TITLE
DynamoDB Sync fails

### ISSUE THREAD

**Issue by marco-lancini** [lyft/cartography#258]
Hi,
I'm observing a weird behaviour with the DynamoDB sync, which fails only on one account.

As you now, I'm running Cartography against a fleet of AWS accounts, all setup in the same way using the Hub and Spoke model (as outlined in [this blogpost](https://www.marcolancini.it/2019/blog-cross-account-auditing/)).

Halfway through the ingestion, Cartography raises the following error (notice that it successfully managed to ingest DynamoDB tables for previous accounts):

```
INFO:cartography.intel.aws.dynamodb:Syncing DynamoDB for region in 'XXX' in account 'XXXX'.
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the ListTables operation: The security token included in the request is invalid
Traceback (most recent call last):
  File "/usr/bin/cartography", line 11, in <module>
    load_entry_point('cartography==0.18.0', 'console_scripts', 'cartography')()
  File "/usr/lib/python3.7/site-packages/cartography/cli.py", line 259, in main
    return CLI(default_sync, prog='cartography').main(argv)
  File "/usr/lib/python3.7/site-packages/cartography/cli.py", line 239, in main
    return cartography.sync.run_with_config(self.sync, config)
  File "/usr/lib/python3.7/site-packages/cartography/sync.py", line 136, in run_with_config
    return sync.run(neo4j_driver, config)
  File "/usr/lib/python3.7/site-packages/cartography/sync.py", line 70, in run
    stage_func(neo4j_session, config)
  File "/usr/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 107, in start_aws_ingestion
    _sync_multiple_accounts(neo4j_session, aws_accounts, config.update_tag, common_job_parameters)
  File "/usr/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 58, in _sync_multiple_accounts
    _sync_one_account(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "/usr/lib/python3.7/site-packages/cartography/intel/aws/__init__.py", line 37, in _sync_one_account
    dynamodb.sync(neo4j_session, boto3_session, regions, account_id, sync_tag, common_job_parameters)
  File "/usr/lib/python3.7/site-packages/cartography/intel/aws/dynamodb.py", line 99, in sync
    common_job_parameters,
  File "/usr/lib/python3.7/site-packages/cartography/intel/aws/dynamodb.py", line 88, in sync_dynamodb_tables
    data = get_dynamodb_tables(boto3_session, region)
  File "/usr/lib/python3.7/site-packages/cartography/intel/aws/dynamodb.py", line 12, in get_dynamodb_tables
    for page in paginator.paginate():
  File "/usr/lib/python3.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/lib/python3.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3.7/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the ListTables operation: The security token included in the request is invalid
```

Have you experienced this before?

**Comment by achantavy** [comment]
Haven't seen this before, has anything changed with the auth config for that particular account?  Our AWS syncs run for a few hours (yeah I know this sucks, we're working on making Cartography faster I promise) so I don't think that it could be a token timeout problem.  The only thing I can think of would be to triple check the permissions of the role.  @SecPrez maybe can weigh in.

**Comment by achantavy** [comment]
Oh one more question, do another AWS services successfully sync on that account?

**Comment by achantavy** [comment]
I might have a related repro.  Here are my steps:

1. Assume the role that fails your DynamoDB sync
1. Open up a python3 console on the Python environment that you use to run Cartography
1. In the python console, run line-by-line
	```
	import boto3
	from neo4j import GraphDatabase
	neo4j_driver = GraphDatabase.driver('bolt://localhost:7687')
	neo4j_session = neo4j_driver.session()
	account_id = "the failing account id"
	common_job_parameters = {'UPDATE_TAG': '1234', "AWS_ID":account_id}
	import cartography.intel.aws
	session = boto3.Session()

	# hacky test stuff
	class Config():
	  def __init__(self):
	    stuff = None
	config = Config()
	config.update_tag = '1234'
	```

1. Then run in the python console (it should):
	```
	cartography.intel.aws._sync_one_account(neo4j_session, session, account_id, '1234', common_job_parameters)
	```
1. And then run in the console and check if this works (it probably will fail with "the security token included in the request is invalid"):
```
cartography.intel.aws.start_aws_ingestion(neo4j_session, config)
```

If you can confirm those results, then I think there is a problem [here](https://github.com/lyft/cartography/blob/34d54e0fc8a95098d0203f1ca0d23fa9b44b7723/cartography/intel/aws/__init__.py#L56), which comes from [here](https://github.com/lyft/cartography/blob/34d54e0fc8a95098d0203f1ca0d23fa9b44b7723/cartography/intel/aws/organizations.py#L27).

Troubleshooting steps
Look for `INFO` messages from boto3 and ensure that the credential method is what you expect.  For example, boto3's logs might say something like "found credentials in ~/.aws/credentials file".  This could be problematic if you are expecting to load the creds from, say, instance metadata.

I applied a patch like this to [here](https://github.com/lyft/cartography/blob/34d54e0fc8a95098d0203f1ca0d23fa9b44b7723/cartography/intel/aws/__init__.py#L56) and it looks like
```python
def _sync_multiple_accounts(neo4j_session, accounts, sync_tag, common_job_parameters):
[...]        
        try:
            boto3_session = boto3.Session(profile_name=profile_name)
        except botocore.exceptions.ProfileNotFound:
            logger.warning("Profile %s not found, trying to create a blank boto3 session.",
                           profile_name)
            boto3_session = boto3.Session()
        _sync_one_account(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
```

This seems to work for my case.  I'll play a bit more but I'll submit the patch soon.  Can you let me know what you think?

**Comment by marco-lancini** [comment]
Hi @achantavy, thanks for coming back to me:

> Haven't seen this before, has anything changed with the auth config for that particular account? 

No, no changes

> Our AWS syncs run for a few hours (yeah I know this sucks, we're working on making Cartography faster I promise) so I don't think that it could be a token timeout problem. 

The failing account is the 3rd on the list, and the crash happens less than 5 minutes since Cartography starts, so I think we can exclude timeout-related problems

> Oh one more question, do another AWS services successfully sync on that account?

Not only other AWS services sync successfully on that account, but DynamoDB itself in other regions works fine. It crashes always on `ap-east-1`:
```
INFO:cartography.intel.aws:Syncing AWS account with ID '<REDACTED>' using configured profile '<REDACTED>'.                                                    
INFO:cartography.intel.aws.iam:Syncing IAM for account '<REDACTED>'.                                                                                      
INFO:cartography.intel.aws.s3:Syncing S3 for account '<REDACTED>'.                                                                                        
INFO:cartography.intel.aws.dynamodb:Syncing DynamoDB for region in 'eu-north-1' in account '<REDACTED>'.                                                  
INFO:cartography.intel.aws.dynamodb:Syncing DynamoDB for region in 'ap-south-1' in account '<REDACTED>'.                                                  
INFO:cartography.intel.aws.dynamodb:Syncing DynamoDB for region in 'eu-west-3' in account '<REDACTED>'.                                                   
INFO:cartography.intel.aws.dynamodb:Syncing DynamoDB for region in 'eu-west-2' in account '<REDACTED>'.                                                   
INFO:cartography.intel.aws.dynamodb:Syncing DynamoDB for region in 'eu-west-1' in account '<REDACTED>'.                                                   
INFO:cartography.intel.aws.dynamodb:Syncing DynamoDB for region in 'ap-northeast-2' in account '<REDACTED>'.                                              
INFO:cartography.intel.aws.dynamodb:Syncing DynamoDB for region in 'ap-northeast-1' in account '<REDACTED>'.                                              
INFO:cartography.intel.aws.dynamodb:Syncing DynamoDB for region in 'sa-east-1' in account '<REDACTED>'.                                                   
INFO:cartography.intel.aws.dynamodb:Syncing DynamoDB for region in 'ca-central-1' in account '<REDACTED>'.                                                
INFO:cartography.intel.aws.dynamodb:Syncing DynamoDB for region in 'ap-east-1' in account '<REDACTED>'.                                                   
ERROR:cartography.sync:Unhandled exception during sync stage 'aws'             
```

**Comment by achantavy** [comment]
Thanks for providing that repro!  This now looks a lot like #231.

See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html: all of the regions that succeeded for you aren't required for opt-in.  The only region that failed was ap-east-1, and that one requires opt-in.

cc: @flyinbutrs

**Comment by marco-lancini** [comment]
I see! Yes, it looks like #231 indeed!

**Comment by flyinbutrs** [comment]
Ah, right. Sorry, it's been a bit nutso in the world lately, this slipped off my radar. I will work on it this week.

**Comment by marco-lancini** [comment]
Hi, is there anything I can do to help with this?

**Comment by marco-lancini** [comment]
I've just raised a PR for this: #299
