### ISSUE TITLE
Handle `NotAction` in IAM policy

### ISSUE THREAD

**Issue by dgreene-r7** [lyft/cartography#26]
I'm seeing an unhandled exception in https://github.com/lyft/cartography/blob/master/cartography/intel/aws/iam.py#L278 if the IAM statement includes a [`NotAction`](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_notaction.html) and no `Action`.

I can provide more information if necessary but as far as I know there's no difference in how an `Action` and `NotAction` should be parsed.

**Comment by achantavy** [comment]
Thanks for pointing this out!  I'll be pushing out a quick and ugly patch today to fix the crash.

However, modeling `NotActions` is going to be tricky and we'll have to think on it.

Currently we represent IAM permissions in the graph between groups and roles in the "positive form" like this: `(AWSGroup)-[:STS_ASSUMEROLE_ALLOW]->(AWSRole)`.  That is, for consistency we only show in the graph what permissions an identity _has_, as opposed to showing what permissions an identity _does-not-have_.

There could be ways to take the `NotAction` and convert them to an equivalent `Actions` list, but that sounds unwieldy.

**Comment by achantavy** [comment]
@dgreene-r7 Please give this pre-release a try: https://pypi.org/project/cartography/0.2.2rc1/

I'll keep this issue open until we can come up with a decision on `NotActions`.

**Comment by dgreene-r7** [comment]
Pre-release seems like it's working great.

In terms of modeling `NotAction`s, my understanding is that there's no programmatic way to retrieve a list of available actions, even on a per-service basis. Until that's possible I don't see any way of deriving possible positive actions based on `NotAction`s.

This is a complicated problem and I'm more than happy to leave it at "don't break on `NotAction`s" :)

**Comment by achantavy** [comment]
Open to help from the community on this one :-)

**Comment by rams3sh** [comment]
A suggestion , cant the "NotAction" be turned to it's corresponding Action  just for the sake of the modelling of data.  Other issues that might be raised / faced by cartography users of similar kind are :-
i. Action / Not Action
ii. Resource / Not Resource
iii. Principal / NotPrincipal (Especially for Role Assumption)
Ref : https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html

For Action , there is a AWS defined universal set from where  the complement / inverted form of Action (i.e. NotAction) could be derived. Policyuniverse has a [function](https://github.com/Netflix-Skunkworks/policyuniverse/blob/99daafd280d30e4155717c8d1113c2b7b8d6f6f2/policyuniverse/expander_minimizer.py#L178) that could be used for doing this task. 

 However for others (Resource/NotResource and Principal/NotPrincipal) , this logic would not work as there is no defined universal set as it is completely user and account dependent.

**Comment by achantavy** [comment]
@rams3sh Thanks for the research, this is very interesting!  We want to use policyuniverse more in cartography, and some of what you're describing sounds like it would fit really well with policyuniverse.  

If you would like to submit a cartography PR, we'd be interested in seeing something help us move toward using policyuniverse wherever we parse IAM policies.
