### ISSUE TITLE
STS_ASSUMEROLE_ALLOW relationship is incorrect

### ISSUE THREAD

**Issue by SecPrez** [lyft/cartography#273]
*Title*: STS_ASSUMEROLE_ALLOW relationship is incorrect

*Description*:
> Cartography maps creates STS_ASSUMEROLE_ALLOW relationships between AWSPrincipals and AWSRoles if the principal's policy contains the sts:AssumeRole permission. However the existence of the permission does not mean the assume role is allowed. 
The documentation at https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html has many more requirements for a role to be able to assume another role. For instance the root account cannot assume roles, and a trust relationship must exist for that role before the AssumeRole is allowed.

> Add any other context about the problem here.

**Comment by achantavy** [comment]
The names might be confusing but this is a bit of a known thing.

For role assumption to work, you need to have both directions:
1. `(RoleA)-[STS_ASSUME_ROLE_ALLOW]->(RoleB)` - RoleA has RoleB listed as a role that it wants to assume.

2. `(RoleB)-[TRUSTS_AWS_PRINCIPAL]->(RoleA)` - RoleB trusts RoleA to assume it.

Reference: https://github.com/lyft/cartography/blob/master/docs/schema/aws.md#awsprincipalawsrole

**Comment by SecPrez** [comment]
Why even map it in if its not trusted? What is the query to determine actual allow roles are in place?

**Comment by achantavy** [comment]
For any given role X, there are two separate lists: (1) the roles that role X wants to assume (this is represented by the STS_ASSUME_ROLE_ALLOW relationship), and the roles that are allowed to assume role X  (represented by TRUSTS_AWS_PRINCIPAL).

The reason why I think we would want to keep both relationships is for red teaming: if you are targeting role X and you know that it trusts a role Y, then you know that if you have control of role Y you could simply add a STS_ASSUME_ROLE_ALLOW from Y to X and then you've reached objective.

**Comment by achantavy** [comment]
> What is the query to determine actual allow roles are in place?

There is none at the moment.  We could add an analysis job to create a new relationship where it checks for both directions and adds a new relationship called, I dunno, `ACTUALLY_CAN_ASSUME_ROLE` or something lol.

**Comment by SecPrez** [comment]
I think fixing the relationship is better. The current relationship also doesn't account for wild cards (https://github.com/lyft/cartography/blob/c39a3bbfc1e8a7f8a6a04658467508b644db1c89/cartography/intel/aws/iam.py#L305) which IAM2.0 can handle.

**Comment by achantavy** [comment]
@SecPrez Please keep the scope of each PR in small chunks and please review Evan's existing work in wildcard expansion here: https://github.com/lyft/cartography/pull/81

I made a similar comment in that review about removing the relationships and just keeping a resulting one - I think that we should keep both sides to properly represent how complicated IAM is.

**Comment by SecPrez** [comment]
I am removing it and replacing it with an RPR from #270. We can discuss it in the PR. It will be a far more elegant solution. In the end STS Assume role is a specific access relationship which is why I am including it as part of IAM2.0
