### ISSUE TITLE
Add billing information

### ISSUE THREAD

**Issue by shanegibbs** [lyft/cartography#30]
It would be very cool to be able to add billing information into the mix here.... :moneybag::moneybag::moneybag:

**Comment by sachafaust** [comment]
Can you add more context as to what you are looking for? Is it data from get_cost_and_usage API or other?

**Comment by shanegibbs** [comment]
Yes, the data from get_cost_and_usage API I believe.

I haven't really thought about how exactly. But I imagine some property related to how much a resource has/is costing. Perhaps the ability to visually size nodes by cost? :thinking:

**Comment by achantavy** [comment]
Thanks for bringing this to our attention, but I don't think we have cycles to work on this soon.
