### ISSUE TITLE
Add support for AWS Transit Gateway

### ISSUE THREAD

**Issue by via-jordan-sokolic** [lyft/cartography#303]
Hi,

It would be a great addition to add support for AWS Transit Gateway, similar to how VPC peering connections are crawled.

I will work on reviewing how peering connections are handled in `intel/aws/ec2.py` and see what I come up with. Is there anywhere else I should be looking?

Thanks for this wonderful project!

**Comment by achantavy** [comment]
Hi there, thanks for taking this on! I think looking at `intel/aws/ec2` is a good start. I hope that you find our [developer guide](https://github.com/lyft/cartography/blob/master/docs/dev/developer-guide.md) and our [how to make an intel module guide](https://github.com/lyft/cartography/blob/master/docs/dev/writing-intel-modules.md) helpful.

Please say hi in Slack; look forward to working together.

**Comment by via-jordan-sokolic** [comment]
Thanks @achantavy! 

I would appreciate some help with building the neo4j query.

Here is the strategy I'm trying to implement for transit gateways:
- merge the transit gateway
- merge the `(AWSAccount)` that owns the gateway as we might not have seen it yet
- set the transit gateway as a `[RESOURCE]` of the owner account
- if `OwnerId != current_aws_account_id`, set the transit gateway as `[SHARED_WITH]` current account

For transit gateway VPC attachments (limiting the scope to VPC attachments for now):
- merge the TGW attachment
- merge the `(AWSVpc)` with which the TGW attachment is associated
- merge the `(EC2Subnet)`s with which the TGW attachment is associated
- set the TGW attachment as `[ATTACHED_TO]` the transit gateway
- set the TGW attachment as `[PART_OF_SUBNET]` for each subnet

Does this strategy make sense?

**Comment by achantavy** [comment]
> - merge the transit gateway
> - merge the (AWSAccount) that owns the gateway as we might not have seen it yet
> - set the transit gateway as a [RESOURCE] of the owner account

This sounds good. I think you can do these tasks in one query with 

```
MERGE (acc:AWSAccount{id:1234})
ON CREATE SET acc.foreign = True

MERGE (tgw:AWSTransitGateway{id:"someid"])
ON CREATE SET < ... >
SET < ... >

MERGE (tgw)<-[r:RESOURCE]-(acc)
ON CREATE SET < ... >
SET < ... .
```
Might need to test and play around with this though; I could be wrong.


> - merge the TGW attachment
> - merge the (AWSVpc) with which the TGW attachment is associated
> - merge the (EC2Subnet)s with which the TGW attachment is associated
> - set the TGW attachment as [ATTACHED_TO] the transit gateway
> - set the TGW attachment as [PART_OF_SUBNET] for each subnet

Now, when we want to attach AWSVpcs and EC2Subnets to the TGWs, I don't think we necessarily need to `MERGE`. I recommend following this `_attach` pattern: https://github.com/lyft/cartography/blob/d339848bcc5bc301a91041cd86992b8cf3c09da4/cartography/intel/aws/rds.py#L156

In that example we match on the EC2Subnet and attach it to a DBSubnetGroup. 

Like all things though, play around with it and see what works. Oh, remember to do cleanup jobs also :)

Does this make sense?

**Comment by via-jordan-sokolic** [comment]
Yes, I think so. Thanks for your suggestion.
Graph databases and cypher are both new to me so I'm getting a bit tripped up in the syntax - specifically when a `WHEN` directive is needed and when not...

I think what I'll do is create a separate `_attach` function specifically for VPC transit gateway attachments in order to attach the attachment to VPCs and subnets. 

Anyway, I hope to have something ready in the next day or two.

**Comment by achantavy** [comment]
Hey @via-jordan-sokolic, do you need help on this? Not meaning to rush you at all or anything like that, just wanted to make myself available :)

**Comment by via-jordan-sokolic** [comment]
Hi @achantavy, thanks for checking in - we're just experiencing some legal hurdles with the CLA unfortunately. As soon as that's squared away we'll re-open the PR and start the review.

**Comment by via-jordan-sokolic** [comment]
Good news 🎉 CLA is signed! Re-opening PR #308 for review.

**Comment by via-jordan-sokolic** [comment]
#308 has been merged (hooray!) so I'm closing this issue.
