### ISSUE TITLE
AssumeRole does not create STS_ASSUMEROLE_ALLOW edge

### ISSUE THREAD

**Issue by arjantop** [lyft/cartography#314]
*Description*:
Edge STS_ASSUMEROLE_ALLOW is not created for the user.
This comes from the line https://github.com/lyft/cartography/blob/66fe5a11a7ecb2ec5689fd6a6515159ff6b03356/cartography/intel/aws/iam.py#L359 where permission is passed in as string but `principal_allowed_on_resource` will iterate over it character-by-character.

*To Reproduce*:
User with assume-role permissions.

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::135704509156:user/user_1"
      },
      "Action": "sts:AssumeRole",
    }
  ]
}
```

- Cartography release version or commit hash: fb68aac03f785a67990b5c31139a539c0798b255
- Python version: 3.7.7

**Comment by achantavy** [comment]
@SecPrez mind taking a look?

**Comment by SecPrez** [comment]
I am making the fix

**Comment by achantavy** [comment]
Thanks @SecPrez!

@arjantop Were you able to see this?
