### ISSUE TITLE
Add support for AWS Simple Queue Service

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#320]
*Title*: *Add support for AWS SQS*

*Description*:
> Describe your idea.  Please be detailed.  If a feature request, please
describe the desired behavior, what scenario it enables, and how it
would be used.

We need support for AWS Simple Queue Service queues. In addition to queues we may need other objects to get a thorough view on our SQS usage.

[optional *Relevant Links*:]
> Any extra documentation required to understand the issue.
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html
- https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ListQueues.html

**Comment by eRaMvn** [comment]
I can help with this. SQS has its own resource policy so maybe we can do the same as S3. Similarly, we may need to map SNS or KMS or Secret Manager as well as they all have resource policy and connected

**Comment by achantavy** [comment]
Thanks @eRaMvn! We talked about this but I'll post it here for everyone else - I recommend copying [this PR](https://github.com/lyft/cartography/pull/323/files) for an initial commit of any new AWS node; just add in one node type with 1 or 2 new relationship types, add tests, add schema docs. Then in future PRs we can add in more node types/connections if necessary.

**Comment by kedarghule** [comment]
Addressed in PR - https://github.com/lyft/cartography/pull/659
