### ISSUE TITLE
Feature request: Create a Docker image

### ISSUE THREAD

**Issue by saidmasoud** [lyft/cartography#33]
Pretty self-explanatory. Would be nice to be able to pull a Docker image instead of having to install all of the dependencies locally. Publishing the image to Docker hub would be awesome as well.

**Comment by sachafaust** [comment]
Coming in https://github.com/lyft/cartography/pull/32

**Comment by ecdavis** [comment]
Closing this as we are not accepting deployment/containerization configuration changes. See #159 for further discussion on this topic.
