### ISSUE TITLE
AWSLambda nodes aren't connected to other nodes

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#348]
**Bug Template**

*Title*: *AWSLambda nodes aren't connected to other nodes*

*Description*:
> What issue is being seen?  Describe what should be happening instead of the bug, for example: Cartography should not crash, the expected value isn't returned, the data schema is wrong, etc.

```
MATCH (a:AWSLambda)-[r:STS_ASSUME_ROLE_ALLOW]->(n) return * limit 30
```
Returns nothing, although we would expect to see the IAM roles they are able to assume.

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.
Run the code.

*Please complete the following information:*:
>  - Cartography release version or commit hash [e.g. 0.12.0 or 95e8e11913e2a44a4d4682506d8364a638ceac69]
>  - Python version: [e.g. 3.7.4]
>  - OS (feel free to omit this if you don't think it's relevant to your issue): [e.g. Ubuntu bla bla, OSX bla bla]

ae6c790c9a799f381b19945a9d2902b6ac5c3ecd

We should ensure that they are connected at minimum to their accounts and verify that they are connected to their IAM roles.

**Comment by marco-lancini** [comment]
Are we saying that `MATCH (a:AWSAccount)-[:RESOURCE]->(l:AWSLambda) return *` returns nothing?

**Comment by achantavy** [comment]
Correct: https://github.com/lyft/cartography/blob/master/cartography/intel/aws/lambda_function.py#L26 We don't create any links to the account 😅  I missed that in review but it's a minor change.

We'll need to double check why the roles aren't getting connected too. I think the int test for this module doesn't verify connections yet.
