### ISSUE TITLE
Analysis Job For Direct Instance Exposure Is Inaccurate

### ISSUE THREAD

**Issue by mdrdannyr** [lyft/cartography#378]
***Analysis Job For Direct Instance Exposure Is Inaccurate***

***Description***:
- There are AWS instances that are publicly exposed, that are not marked as such by the analysis job. 
- This happens specifically when instances have **publicipaddress** but do not have **publicdnsname**

**Cause:** 

https://github.com/lyft/cartography/blob/master/cartography/data/jobs/analysis/aws_ec2_asset_exposure.json#L9

`WHERE (EXISTS(instance.**publicdnsname**) AND instance.**publicdnsname** <> '')`

**Root Cause Analysis:** 

- Instances can be public without having a publicdnsname. . 
- Instances are also marked with publicdnsname = empty, instead of setting the value to None. This causes ambiguity when running queries. Looking for instances that have publicipaddress but don't have publicdnsname, you may use: 

`match(n:EC2Instance) where exists(n.publicipaddress) and not exists(n.publicdnsname) return count(n)`

However, this would be incorrect as the publicipaddress and publicdnsname will always exist, it may just be empty. 

Therefore, the following query would be correct: 

`match(n:EC2Instance) where not n.publicipaddress='' and n.publicdnsname='' return count(n)`

Slack Discussion can be found here: https://lyftoss.slack.com/archives/CTZUQL0KX/p1596040314140000

***To Reproduce*:**
> Create a public instance with no publicdnsname in AWS. 
> Run the scan
> Note that the instance is not marked as exposed to internet. 

*Please complete the following information:*:
>  - Cartography release version or commit hash: f57a9bdddb89244d392e09591fcc475b89419a46

**Proposed Next Steps:**

- Changing the WHERE clause to use publicipaddress would solve this issue
- Discussion around empty vs None when inserting fields with non-existent values is needed.

**Comment by achantavy** [comment]
> Changing the WHERE clause to use publicipaddress would solve this issue

In my own environment I did not see any nodes where publicipaddress was set without publicdnsname, but this step sounds reasonable.

> Discussion around empty vs None when inserting fields with non-existent values is needed.

Going forward, empty string is not an acceptable value for non-existent values because it leads to weird behaviors such as #353. 

When fixing that issue I forgot to account for the analysis job (my bad). @mdrdannyr, do you have cycles to do the fix? @marco-lancini or myself can approve. No worries if not.

**Comment by mdrdannyr** [comment]
Great, i'll hopefully find some time to send a PR this week. So, just to discuss changes for this specific issue:

**1)** Updating the WHERE statement to use **publicipaddress** instead of **publicdnsname**.

Therefore updated https://github.com/lyft/cartography/blob/master/cartography/data/jobs/analysis/aws_ec2_asset_exposure.json#L9: 
 
`"query": "MATCH (:IpRange{id: '0.0.0.0/0'})-[:MEMBER_OF_IP_RULE]->(:IpPermissionInbound)-[:MEMBER_OF_EC2_SECURITY_GROUP]->(group:EC2SecurityGroup)<-[:MEMBER_OF_EC2_SECURITY_GROUP|NETWORK_INTERFACE*..2]-(instance:EC2Instance)\nWITH instance\nWHERE (EXISTS(instance.publicipaddress) AND instance.publicipaddress <> '') AND (NOT EXISTS(instance.exposed_internet_type)) OR (NOT 'direct' IN instance.exposed_internet_type)\nSET instance.exposed_internet = true, instance.exposed_internet_type = coalesce(instance.exposed_internet_type , []) + 'direct';",
`

**Questions:** 

1) Do we need `AND instance.publicipaddress <> ''`? 
2) Are we doing any work to update the Neo4j ingestion of EC2instances so that empty strings are not inserted for fields that are missing?
3) If work has already been conducted then removing the code snippet in Q1 makes sense. If not, i can tackle removing empty strings when we write EC2Instances to neo4j and then removing code snipper in Q1 will make sense.

**Comment by achantavy** [comment]
1. No, publicipaddress now is set to an actual value or None: https://github.com/lyft/cartography/blob/0a1fde25f0bc62cdf8f1e053ebc4c393ff042f05/cartography/intel/aws/ec2/instances.py#L176

2. Yes, see #351 and #354
