### ISSUE TITLE
Add full support for ec2::Subnet

### ISSUE THREAD

**Issue by krisek** [lyft/cartography#399]
As far as I see at the moment subnet information is loaded only from referring objects, the full subnet information is not available in the database, which means that vpcid, cidrblock and other interesting parameters are missing.

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Subnet.html
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html?highlight=describe_subnets#EC2.Client.describe_subnets

I might give a try implementing it, but would be so nice not to deep dive from scratch, maybe it is alredy in the queue somewhere.

**Comment by achantavy** [comment]
Thanks for making note of this. If you want to work on this we can help, say hi in Slack :-).

**Comment by krisek** [comment]
Hi, a raised a few topics on Slack the core of the new functionality is there on my dev instance.

**Comment by krisek** [comment]
Fixed with https://github.com/lyft/cartography/pull/401
