### ISSUE TITLE
ec2 network-interfaces support

### ISSUE THREAD

**Issue by krisek** [lyft/cartography#414]
*Title*: Import ec2 network interfaces

*Description*:
Import all EC2 Network Interfaces, so that ELB IPs can be identified from the database

Import the output of ec2 describe-network-interfaces call.

I assume everything is there the only new relation which will come in will be 

(LoadBalancer|LoadBalancerV2)-[NETWORK_INTERFACE]->(NetworkInterface)

**Comment by krisek** [comment]
I implemented this iin https://github.com/krisek/cartography/tree/%23407-ec2security-group-fix, there are some things to align.

1. I had to create a new node for the IP addresses --- one network interface can have several IP addresses, these are not 'public' AWS objects, but still I couldn't come to a better solution to put them in the database. Actually it is not so bad (*)... this way we can query IP addresses directly. The respective relation looks like this:

     (NetworkInterface)-[:PRIVATE_IP_ADDRESS]->(EC2PrivateIp)

2. As the NetworkInterface data model consist of a lot of optional elements (Attachment, Association, PublicIp) I implmeneted a filter [cycle](https://github.com/krisek/cartography/blob/c0039a2eaa3b2cd83d24f0d9b3a750c391f8aa6e/cartography/intel/aws/ec2/network_interfaces.py#L26-L74) that extracts the relevant records from the overall NetworkInterfaces data structure. Is this OK? Maybe I can recfactor it to be more elegant -- I'm not 100% sure how missing attributes in input data are handled by Neo4j.

I still need to write the schema update and the tests, so this is the right point to change anything if required.

(*) It is actually very bad: the cloud/SDN is about to get rid of IP dependencies, and what am I doing here: I keep track of IP addresses --- on the other hand environments needs to be managed and people seem liking IP addresses :smile:.

**Comment by achantavy** [comment]
I think we can use multiple labels:

Use the `:EC2PrivateIp` label and also add the more generic `:Ip` label (kinda like how we have `:Instance:EC2Instance` and `:Instance:GCPInstance`).

What do you think?

> the cloud/SDN is about to get rid of IP dependencies, and what am I doing here: I keep track of IP addresses

Ha, I feel like having viz on IPs will always be important regardless of the abstractions eventually used by SDN; we'll see.

**Comment by krisek** [comment]
> Use the `:EC2PrivateIp` label and also add the more generic `:Ip` label

Agreed, implemented with [9f3a00](https://github.com/krisek/cartography/commit/9f3a00e2d2d4425293b587b56a43c1e87bb6b099) 

I've started working on the test cases, then schema update and the PR comes.

**Comment by krisek** [comment]
> > Use the `:EC2PrivateIp` label and also add the more generic `:Ip` label
> 
> Agreed, implemented with [9f3a00](https://github.com/krisek/cartography/commit/9f3a00e2d2d4425293b587b56a43c1e87bb6b099)

As I update the documentation it became appearent that the Ip node is not appropriate here, as the id of an Ip node is the ip address: this doesn't work in AWS (and actually I doubt it works anywhere) as an IP is always in context with an interface. Duplicate ips in an environment would be abstracted as single nodes which doesn't work. 

I revert now the change and we align later if this needs to be resolved (ever).
