### ISSUE TITLE
Error when trying to sync data

### ISSUE THREAD

**Issue by thomlink** [lyft/cartography#427]
*Title*: Error when trying to sync data by calling: `cartography --neo4j-uri bolt://localhost:7687`

*Description*:

I am trying to set cartography up on AWS EC2. I followed the instructions for installing [cartography](https://github.com/lyft/cartography/blob/master/docs/setup/install.md) & [neo4j](https://neo4j.com/docs/operations-manual/current/installation/linux/rpm/#linux-rpm-install-standard) and configuring [aws](https://github.com/lyft/cartography/blob/master/docs/setup/config/aws.md) (for single account setup). 

When I get to the step of 

> Finally, to sync your data:
> 
> For one account using the default profile defined in your AWS config file, run
> 
> cartography --neo4j-uri <uri for your neo4j instance; usually bolt://localhost:7687>

I run `cartography --neo4j-uri bolt://localhost:7687` and get the following error:

```
ERROR:cartography.sync:Unable to connect to Neo4j using the provided URI 'bolt://localhost:7687', an error occurred: 'Failed to establish connection to ('127.0.0.1', 7687) (rea
son [Errno 111] Connection refused)'. Make sure the Neo4j server is running and accessible from your network.
```

I have tried using both the User created in the aws configure guide (which has the SecurityAudit policy attached) and an admin user.

I don't know how to  `Make sure the Neo4j server is running and accessible from your network` exactly but I followed all the steps on the deployment [guide](https://neo4j.com/docs/operations-manual/current/installation/linux/rpm/#linux-rpm-install-standard) (as linked above) and ran the command
``` 
rpm -qa | grep neo
```
which returned `neo4j-4.1.3-1.noarch` confirming it is installed.

*Please complete the following information:*:
>  - Cartography release version: 0.28.0
>  - Python version: 3.7.4
>  - OS: Amazon Linux 2

Hopefully it is a small error I have made somewhere along the line

Thanks for your help!

**Comment by achantavy** [comment]
Hi @thomlink, we only support Neo4j 3.5.x. Can you install that and try again and let us know how it goes?

**Comment by thomlink** [comment]
Downgraded to version `3.5.22` and still get the same error

**Comment by marco-lancini** [comment]
Just to confirm, there is direct network connectivity between cartography and neo4j, right?

**Comment by achantavy** [comment]
It doesn't look like you're getting an auth error, but another thing to check is you may also need to change `/path/to/neo4j/conf/neo4j.conf` and set `dbms.security.auth_enabled=false`.

**Comment by thomlink** [comment]
> Just to confirm, there is direct network connectivity between cartography and neo4j, right?

I installed neo4j on my EC2 instance and I'm a bit confused as to where Cartography is meant to be installed? From the instructions I assumed on the EC2 instance also, but maybe thats not right. 

If I am supposed to install Cartography elsewhere, what would the URI be for this command?
`cartography --neo4j-uri <uri for your neo4j instance; usually bolt://localhost:7687>`

Thanks for your help, sorry for any confusion

**Comment by krisek** [comment]
> I assumed on the EC2 instance also

You can install on the same instance. For small environments it is an overkill to have Cartography on separate infra.

> If I am supposed

No, no you are not supposed. But if... just replace localhost with the DNS name/IP address of the Neo4j instance -- and ensure Cartography can reach Neo4j (security group, local firewall, whatsoever)

**Comment by thomlink** [comment]
> It doesn't look like you're getting an auth error, but another thing to check is you may also need to change `/path/to/neo4j/conf/neo4j.conf` and set `dbms.security.auth_enabled=false`.

Just checked and this was already the case. Still got the same problem.

> You can install on the same instance. For small environments it is an overkill to have Cartography on separate infra.
-->They are installed on the same instance, therefore I can confirm that
>there is direct network connectivity between cartography and neo4j, right?

**Comment by krisek** [comment]
Drop by on Slack and we discuss. I'd be surprised if this was a Cartography software issue.

**Comment by thomlink** [comment]
Solved: Neo4j was not actually running 

To fix:
`service neo4j start`

**Comment by achantavy** [comment]
Ahh glad you got this working, good idea to add this to the doc actually
