### ISSUE TITLE
GCP Sync attempts to access deleted projects

### ISSUE THREAD

**Issue by jalseth** [lyft/cartography#447]
**Bug Template**

*Description*:
> The GCP sync currently attempts to sync from projects that have been deleted, which returns 403 unauthorized. This slows down processing and unnecessarily adds stale data to the database.

*To Reproduce*:
> 1. Delete a GCP project
> 2. Run Cartography
> 3. Observe the 403 error in the log for the deleted project

*Logs*:
> N/A

*Screenshots*:
> N/A

*Please complete the following information:*:
>  - Cartography ver: 0.28.0 via pip
>  - Python version: Python 3.8.5
>  - OS (feel free to omit this if you don't think it's relevant to your issue): Ubuntu 20.04.1

**Comment by carise** [comment]
I'm interested in helping with this, will get setup with Cartography first and then jump on this.
