### ISSUE TITLE
AWS_CONFIG_FILE option with aws-sync-all-profiles leads to botocore.exceptions.NoRegionError: You must specify a region

### ISSUE THREAD

**Issue by elapse2039** [lyft/cartography#486]
When more than a single "default" profile and creds are defined in ~/.aws/ the following command will throw an exception when it attempts to change AWS Region.

AWS_CONFIG_FILE=~/.aws/config cartography --neo4j-uri bolt://localhost:7687 --neo4j-user neo4j --neo4j-password-env-var NEO4J_PASSWORD_ENV_VAR --aws-sync-all-profiles

So far the only way I've successfully run cartography is a single default account.  Specifying a profile name, a config file always ends in this exception.

The config file looks like this:
[default]
region=us-east-1
output=json
[production]
region=us-east-2
output=json
[testing]
region=us-east-1
output=json

There is a corresponding credentials file for each profile. 

Attached is the exception trace back on cartography 0.30 on ubuntu 20.04

[boto3-exception-cartography-aws-config.txt](https://github.com/lyft/cartography/files/5653716/boto3-exception-cartography-aws-config.txt)

**Comment by serain** [comment]
As a workaround, try setting AWS_DEFAULT_REGION env var to any default

**Comment by elapse2039** [comment]
That worked! Thanks for the fast response.  Perhaps a side-note in the setup README would help others while this is a workaround.
