### ISSUE TITLE
DNS records and LoadBalancers fail to link due to inconsistent letter case

### ISSUE THREAD

**Issue by serain** [lyft/cartography#490]
*Title*: AWSDNSRecord fails to link to LoadBalancer and LoadBalancerV2 when they don't use the same letter case

*Description*:
A chunk of our AWS DNS records don't get linked to the respective load balancers by Cartography.

This appears to be because load balancer's "DNS name" can have uppercase characters (i.e. `Test-1ABC-1234.elb.eu-west-1.amazonaws.com`), while the matching Route53 record value may be lowercase (i.e. `test-1abc-1234.elb.eu-west-1.amazonaws.com`). Note that the inverse is also true. As DNS itself is case insensitive, there's technically nothing wrong with the above, however Cartography is looking for an exact match:

```
    MATCH (n:AWSDNSRecord) WITH n MATCH (l:LoadBalancer{dnsname: n.value})
```

Obviously, the root of the problem is inconsistency in the way some of our teams are creating their load balancers/DNS records, but this appears to be the result of some inconsistent automation tools, likely outside of our control (still investigating the source tbh).

I suspect we won't be the only Cartography users suffering from this inconsistency though and I believe this should be handled by Cartography by either:

* sanitising DNS names/records on ingestion (i.e. lowercasing DNS names of assets and DNS record values)
* doing a case insensitive match in Neo4j when linking resources that can suffer from this discrepancy

*To Reproduce*:
* Create a load balancer with a name that includes uppercase letters.
* Note the DNS name of the load balancer, it'll contain uppercase characters
* Create a DNS record alias for the load balancer. The value of the DNS record should be the lowercase DNS name of the load balancer.
* Run cartography and note that the two resources are not linked.

*Please complete the following information:*:
- Cartography release: 0.30.0
- Python version: 3.8.5

**Comment by achantavy** [comment]
Thanks for the detailed write-up!

> doing a case insensitive match in Neo4j when linking resources that can suffer from this discrepancy

I think this is the way to go here.
