### ISSUE TITLE
AWS S3 get_bucket_location fails with Access Denied

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#492]
*Description*:
> What issue is being seen?  Describe what should be happening instead of the bug, for example: Cartography should not crash, the expected value isn't returned, the data schema is wrong, etc.

S3 get_bucket_location() can fail with a permissions error. Given that as much of cartography should run with only SecurityAudit, we should handle this exception gracefully.

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.

Run the s3 sync on an account that does not have get_bucket_location permissions.

*Logs*:
> If applicable, copy and paste your console log with the failing stack trace.

```
  File "/{PATH/cartography/intel/aws/__init__.py", line 98, in _sync_multiple_accounts
    _sync_one_account(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "/{PATH/cartography/intel/aws/__init__.py", line 29, in _sync_one_account
    s3.sync(neo4j_session, boto3_session, account_id, sync_tag, common_job_parameters)
  File "/{PATH/cartography/util.py", line 58, in timed
    result = method(*args, **kwargs)
  File "/{PATH/cartography/intel/aws/s3.py", line 361, in sync
    bucket_data = get_s3_bucket_list(boto3_session)
  File "/{PATH/cartography/util.py", line 58, in timed
    result = method(*args, **kwargs)
  File "/{PATH/cartography/intel/aws/s3.py", line 21, in get_s3_bucket_list
    bucket['Region'] = client.get_bucket_location(Bucket=bucket['Name'])['LocationConstraint']
  File "/{PATH/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/{PATH/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied
```

*Please complete the following information:*:
>  - Cartography release version or commit hash [e.g. 0.12.0 or 95e8e11913e2a44a4d4682506d8364a638ceac69]

0f71b3f0246665d5fa065afa2e3dc46c22d6c689

*Additional context*:
> Add any other context about the problem here.

This is an unintended side effect of https://github.com/lyft/cartography/pull/470.

**Comment by achantavy** [comment]
cc: @shabin-slr FYI. I think I have a quick fix but I haven't tested (tied up with other things right now). If you have time and are able to write a fix and test it faster than me that'd be super helpful.

**Comment by achantavy** [comment]
I tested this and it should work  now.

**Comment by shabin-slr** [comment]
@achantavy, SecurityAudity policy has an Allow rule "s3:GetBucket*". Isn't this necessary to call "s3.get_bucket_location()" ?
