### ISSUE TITLE
How to authenticate AWS if AWS account is manage by Okta?

### ISSUE THREAD

**Issue by danielwangksu** [lyft/cartography#50]
I'm trying to use cartography but my AWS account is managed by Okta hence there is no token and session key in my .aws/config. I'm wondering if there is a solution for cartography to login AWS in this setup?

**Comment by achantavy** [comment]
Try 

1. log in to AWS via OKTA
2. Open the IAM service
3. Click 'Users'
4. Click on your own username, might need to filter for it
5. Click "Security Credentials"
6. Create access key
7. Use that key and key ID in a config or a credentials file

Granted, this all depends on if your team/organization allows you to create an access key :-)

**Comment by danielwangksu** [comment]
Thank you for your help. I will contact my organization to get access.

**Comment by achantavy** [comment]
Cool, good luck!

**Comment by himanshudas** [comment]
> Try
> 
>     1. log in to AWS via OKTA
> 
>     2. Open the IAM service
> 
>     3. Click 'Users'
> 
>     4. Click on your own username, might need to filter for it
> 
>     5. Click "Security Credentials"
> 
>     6. Create access key
> 
>     7. Use that key and key ID in a config or a credentials file
> 
> 
> Granted, this all depends on if your team/organization allows you to create an access key :-)

Apologies, but this is not the best way. Please, configure aws-okta and use you could pass ~/.aws/config: https://github.com/segmentio/aws-okta

**Comment by danielwangksu** [comment]
> > Try
> > ```
> > 1. log in to AWS via OKTA
> > 
> > 2. Open the IAM service
> > 
> > 3. Click 'Users'
> > 
> > 4. Click on your own username, might need to filter for it
> > 
> > 5. Click "Security Credentials"
> > 
> > 6. Create access key
> > 
> > 7. Use that key and key ID in a config or a credentials file
> > ```
> > Granted, this all depends on if your team/organization allows you to create an access key :-)
> 
> Apologies, but this is not the best way. Please, configure aws-okta and use you could pass ~/.aws/config: https://github.com/segmentio/aws-okta

Hi @himanshudas do you mean to get the access key and put it in the `~/.aws/config` file? My current `config` file only contains `role_arn` and relies on MFA to authentication.
