### ISSUE TITLE
fix syncing multiple AWS accounts in parallel

### ISSUE THREAD

**Issue by krisek** [lyft/cartography#503]
Bug

*Title*: *Fix syncing multiple AWS accounts in parallel*

*Description*:
At the moment if you are syncing more AWS accounts, you have to sync all of them in a shot as the cleanup job cleans all non-updated accounts. This is not inteded behaviour, it has to be fixed.

**Comment by achantavy** [comment]
> the cleanup job cleans all non-updated accounts

Can you please point out where this happens? This is not intended behavior and is absolutely a bug.

**Comment by krisek** [comment]
I'll submit a pull request with the issues I found.
