### ISSUE TITLE
AWS: Add support for Internet Gateway

### ISSUE THREAD

**Issue by aashishgaba-cn** [lyft/cartography#512]
*Title*: *Add support for Internet Gateway*

*Description*:
As of now, Cartography doesn't support Internet Gateway.
An internet gateway allows communication between your VPC and the internet.

The relationships that I've identified are

(AWSAccount) - [RESOURCE] -> (EC2InternetGateway)
(EC2InternetGateway) -[ATTACHED_TO]-> (AWSVpc)

*Relevant Links*
[Internet Gateway](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html)

**Comment by cpollard0** [comment]
Started working on this here https://github.com/lyft/cartography/pull/555
