### ISSUE TITLE
AWS apigateway sync - TooManyRequests exception

### ISSUE THREAD

**Issue by achantavy** [lyft/cartography#559]
*Title*: *One line description*

*Description*:
> What issue is being seen?  Describe what should be happening instead of the bug, for example: Cartography should not crash, the expected value isn't returned, the data schema is wrong, etc.

APIGateway sync crashes with TooManyRequests for `get_rest_api_details`.

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.

Run apigateway sync on account that is experiencing API quota issues.

*Logs*:
> If applicable, copy and paste your console log with the failing stack trace.

```
File "{PATH}/cartography/cartography/intel/aws/apigateway.py", line 359, in sync_apigateway_rest_apis
for api_id, stage, certificate, resource, policy in stages_certificate_resources:
botocore.errorfactory.TooManyRequestsException: An error occurred (TooManyRequestsException) when calling the GetResources operation: Too Many Requests
result = method(*args, **kwargs)
File "{PATH}/cartography/cartography/intel/aws/apigateway.py", line 296, in load_rest_api_details
aws_requested_syncs=aws_requested_syncs, # Could be replaced later with per-account requested syncs
for page in response_iterator:
sync_apigateway_rest_apis(neo4j_session, boto3_session, region, current_aws_account_id, update_tag)
File "{PATH}/cartography/cartography/util.py", line 61, in timed
File "/code/venvs/venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
raise error_class(parsed_response, operation_name)
resources = get_rest_api_resources(api, client)
File "{PATH}/cartography/cartography/intel/aws/apigateway.py", line 46, in get_rest_api_details
result = method(*args, **kwargs)
```

*Please complete the following information:*:
>  - Cartography release version or commit hash [e.g. 0.12.0 or 95e8e11913e2a44a4d4682506d8364a638ceac69]

047a6bd1820e846e70bda4c6ddc18027da39e20a

*Additional context*

- Going forward we should think of a generic way of handling these API limits. AWS EMR sync handled it with sleeps: https://github.com/lyft/cartography/blob/047a6bd1820e846e70bda4c6ddc18027da39e20a/cartography/intel/aws/emr.py#L29 - maybe we could apply this one-off here as well.

**Comment by cpollard0** [comment]
Boto3 should have built in retry with backoff and jitter. Have you considered changing the number of retries and letting the library handle it? Default is 3, upping it to something higher may fix it without a lot of effort.
