### ISSUE TITLE
Pull AWS asset tag into the graph

### ISSUE THREAD

**Issue by sachafaust** [lyft/cartography#56]
Pull the aws asset tags for all AWS assets and put them in the graph.

**Comment by bobrich** [comment]
Have been thinking about trying this out but am wondering how you would model it.  Tags as attributes of each node or as standalone nodes with links to each object that has the tag name/value?

(Also does the Lyft team have a Slack or Gitter where Cartography is discussed?  Lots of other questions)

**Comment by tobli** [comment]
I have experimented with this locally. This simple model seems to work great in my tests:
`MATCH (tag:Tag {key:"Name"})-[r:TAGGED {value:"foo"})->(n) RETURN tag, r, n`
I'd by happy to contribute a PR.

**Comment by everglory99** [comment]
Hi @tobli, I am very interested in knowing more about your approach on tags. Would you please tell us more how you can pull tags into the graph? A PR is very much appreciated, thanks!

**Comment by tobli** [comment]
I’m putting together a PR for initial tag support. Will push as soon as I get a little more time to prepare it.

**Comment by tobli** [comment]
Pushed https://github.com/lyft/cartography/pull/174 with initial tag support. I'd be happy to tweak based on feedback.
