### ISSUE TITLE
0.32.0 release not pushed to pypi

### ISSUE THREAD

**Issue by steakunderscore** [lyft/cartography#561]
The 0.32.0 release is missing from [pypi](https://pypi.org/project/cartography/#history)

Could be related to: #460

**Comment by achantavy** [comment]
Thanks for filing an issue to track this. We migrated from TravisCI to GitHub Actions when Travis moved from *.org to *.com (see https://github.com/lyft/cartography/pull/524). We'll need to update our GitHub Actions config with our pypi connection information. Stay tuned.

**Comment by achantavy** [comment]
This is now fixed in #568!
