### ISSUE TITLE
Elasticache sync Error - Unhandled exception during sync stage 'aws'

### ISSUE THREAD

**Issue by lgomezma** [lyft/cartography#581]
*Title*: Elasticache Error - Unhandled exception during sync stage 'aws' - Cannot merge node using null property value for id

*Description*:
> AWS Elasticache sync is crashing and causing Cartography to stop running. This seems to happen when the elasticache cluster is empty on a region or no `NotificationConfiguration`.

*To Reproduce*:
> Try to run aws elasticache sync with empty cluster or a cluster without NotificationConfiguration.

*Logs*:
> Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/cartography/sync.py", line 73, in run stage_func(neo4j_session, config) File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 68, in timed return method(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 196, in start_aws_ingestion _sync_multiple_accounts( File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 133, in _sync_multiple_accounts _sync_one_account( File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/__init__.py", line 57, in _sync_one_account RESOURCE_FUNCTIONS[func_name](**sync_args) File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 68, in timed return method(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/elasticache.py", line 108, in sync load_elasticache_clusters(neo4j_session, clusters, region, current_aws_account_id, update_tag) File "/usr/local/lib/python3.9/site-packages/cartography/util.py", line 68, in timed return method(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/cartography/intel/aws/elasticache.py", line 82, in load_elasticache_clusters neo4j_session.run( File "/usr/local/lib/python3.9/site-packages/neo4j/__init__.py", line 503, in run self._connection.fetch() File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 419, in fetch return self._fetch() File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 461, in _fetch response.on_failure(summary_metadata or {}) File "/usr/local/lib/python3.9/site-packages/neobolt/direct.py", line 755, in on_failure raise CypherError.hydrate(**metadata) neobolt.exceptions.ClientError: Cannot merge node using null property value for id

*Please complete the following information:*:
>  - Cartography release version 0.33.3
>  - Python version: 3.9

*Additional context*:
> It looks like the UNWIND query that we use on `load_elasticache_clusters` has issues with empty clusters. Also we assume that a cluster always has `NotificationConfiguration` in the query ```MERGE (topic:ElasticacheTopic{id: elasticache_cluster.NotificationConfiguration.TopicArn})``` which doesn't seem to be the case and causes the query to break.

**Comment by achantavy** [comment]
>  MERGE (topic:ElasticacheTopic{id: elasticache_cluster.NotificationConfiguration.TopicArn})

Thanks for digging into this. Yeah, that's a fragile assumption that we should fix. Rather than add another handler to that sync, I'd prefer to address the root problem by only merging in ElasticacheTopics if they exist.

**Comment by lgomezma** [comment]
I agree, I'm not familiar with Elasticache, hence the error handling as a temp solution. This is actually breaking the aws sync and cartography for us.
