### ISSUE TITLE
Already Synced Data getting deleted

### ISSUE THREAD

**Issue by sing22** [lyft/cartography#587]
**Bug Template**

*Title*: *Already Synced Data getting deleted*

*Description*:
> If you execute SYNC as multiple separate runs for multiple accounts and not doing `--aws-sync-all-profiles`, the very next SYNC execution wipes out the Synced data of the first run. (doesnt matter if the second/next SYNC results into an error or not)

*To Reproduce*:
> **Step 1**: `AWS_PROFILE=aws-account-1 cartography --neo4j-uri bolt://localhost:7687`
All good Sync Success for a particular AWS Account. Fired a query on the Neo4j UI and got the results. Happy me.
**Step 2**: `AWS_PROFILE=aws-account-2 cartography --neo4j-uri bolt://localhost:7687`
Account 2 Sync failed with an exception: botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://cf-templates-pg7wx8u0edg3-eu-west-1.s3.EU.amazonaws.com/?acl"
>As said, it does NOT matter if second/next execution runs into an error.

*Please complete the following information:*:
>  - Cartography release version or commit hash : 0.34.0
>  - Python version: 3.7.9
>  - OS (feel free to omit this if you don't think it's relevant to your issue): Amazon Linux release 2 (Karoo) (LSB Version:	:core-4.1-amd64:core-4.1-noarch)

**Comment by achantavy** [comment]
Hey @sing22, we talked on Slack a bit about this, but do you know specifically which node types got deleted? This will help me narrow down where to look.

For the most part, our cleanup jobs are meant to  only

**Comment by sing22** [comment]
😮  Release `0.34.1` didnt fix this issue. I executed sync for only one profile and the sync failed due to #574 and it wipes out/deletes my already synced data for 3 AWS Accounts. :( .
