### ISSUE TITLE
Offline Data Collection and Sync

### ISSUE THREAD

**Issue by rams3sh** [lyft/cartography#61]
It would be great if there is an offline mode of syncing the data to the neo4j instance.

Being an auditor , it would be extremely useful , if there is a collector script / module that can collect all the required information required for the cartographer tool to sync with neo4j. Then the collected json exports can be taken and synced to a neo4j instance in another system for later analysis.

**Comment by achantavy** [comment]
This is a neat idea!  Unfortunately we don't have the cycles soon to get to it though.

**Comment by sachafaust** [comment]
@rams3sh you could backup the neo4j db which are plain files. Would that work?

I've done it by simply copying the directory but Neo4j has tooling for it also - https://neo4j.com/docs/operations-manual/current/backup/performing/

**Comment by rams3sh** [comment]
> @rams3sh you could backup the neo4j db which are plain files. Would that work?
> 
> I've done it by simply copying the directory but Neo4j has tooling for it also - https://neo4j.com/docs/operations-manual/current/backup/performing/


@sachafaust  Your method would require me to install the neo4j in the collection machine first and then backup that data and transfer to a local neo4j instance and analyze. However , I would not want to install anything in the collection endpoint apart from a basic aws cli which woud be used by the Cloud Admins for daily operations. 

Actually , reason for my ask was, most of the times during the audit the clients do not allow to  install anything on their machine and expect to be given a simple script (mostly a basic shell script without much dependency except for aws cli) to obtain a set of required evidence from aws which could be later passed on by them to the auditors. In a scenario like this , the present mechanism of live sync of cartography would not work nor would the local installation of neo4j, for backup of the directory as you suggested.  Hence my ask for an offline mechanism for sync.
