### ISSUE TITLE
Job Name set to None

### ISSUE THREAD

**Issue by Zenthere** [lyft/cartography#689]
**Bug*

*Job Name set to None*: *Job function from_json() always omits the short_name, resulting in Output that always says None instead of job name*

*Description*:
> What issue is being seen?  Describe what should be happening instead of the bug, for example: Cartography should not crash, the expected value isn't returned, the data schema is wrong, etc.

I notice that in the output I would see many instances of the line(s):
`INFO:cartography.graph.statement:Completed None statement #None` 

This appears because in https://github.com/lyft/cartography/blob/ed1d234b9dcf98593307af08532b0920a3b72534/cartography/graph/job.py#L82 the short_name is omitted to _get_statements_from_json

*To Fix*: adding the passed in short_name clarifies the messages greatly

*To Reproduce*:
> Steps to reproduce the behavior.  Provide all data and inputs required to reproduce the issue.

This seems to always occur, just run a normal cartography run

*Logs*:
> If applicable, copy and paste your console log with the failing stack trace.
Note: **BUGBUG** lines are my own diagnostic logging

```
INFO:cartography.graph.job:>>> #BUGBUG droped short_name aws_ec2_asset_exposure
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.statement:Completed None statement #1
INFO:cartography.graph.statement:Completed None statement #2
INFO:cartography.graph.statement:Completed None statement #3
INFO:cartography.graph.statement:Completed None statement #4
INFO:cartography.graph.statement:Completed None statement #5
INFO:cartography.graph.statement:Completed None statement #6
INFO:cartography.graph.job:Finished job aws_ec2_asset_exposure
INFO:cartography.graph.job:>>> #BUGBUG droped short_name aws_ec2_keypair_analysis
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.statement:Completed None statement #1
INFO:cartography.graph.statement:Completed None statement #2
INFO:cartography.graph.statement:Completed None statement #3
INFO:cartography.graph.statement:Completed None statement #4
INFO:cartography.graph.job:Finished job aws_ec2_keypair_analysis
```

*Please complete the following information:*:
>  - Cartography release version or commit hash [e.g. 0.12.0 or 95e8e11913e2a44a4d4682506d8364a638ceac69]
>  - Python version: [e.g. 3.7.4]
>  - OS (feel free to omit this if you don't think it's relevant to your issue): [e.g. Ubuntu bla bla, OSX bla bla]

*Additional context*:
> Add any other context about the problem here.

**Comment by achantavy** [comment]
Reopening - this issue still exists in 0.94.0rc1.


EMR
```
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.job:Finished job EMRCluster
```


Inspector
```
INFO:cartography.intel.aws.inspector:Running AWS Inspector cleanup
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.job:Finished job AWSInspectorFinding
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.statement:Completed None statement #None
INFO:cartography.graph.job:Finished job AWSInspectorPackage
```

I suspect there is a problem with how the data model passes names to the GraphJob class.
