### ISSUE TITLE
Lyft icon in Lyft app but google maps does work

### ISSUE THREAD

**Issue by datatalking** [lyft/cartography#731]
**Feature request template**

*Which lane to be in is covered*: when the Lyft driver goes to find directions and can't see the turn because it's covered by the Lyft app.￼ there is no directions option in the Lyft version

*Description*:

I have a video I took and will add more detail so 

[optional *Relevant Links*:]
> Any extra documentation required to understand the issue.

**Comment by achantavy** [comment]
Hi @datatalking - this is just an open source project owned by Lyft, not a Lyft support channel, you can contact support here https://help.lyft.com/hc/en-us
