### ISSUE TITLE
AWS Sync: Try all AWS accounts, and raise Exception afterwards

### ISSUE THREAD

**Issue by ramonpetgrave64** [lyft/cartography#773]
*Title*: *Try all AWS accounts, and raise Exception afterwards*

*Description*:
Sometimes a single AWS account's sync could fail. In such situations, we more likely want to proceed with the rest of our accounts, but still be notified of the failure.

I propose to wrap `_sync_one_account` into a try-catch, invoke `logger.exception` for the failures, and then finally raise another exception listing the accounts that failed.

https://github.com/lyft/cartography/blob/master/cartography/intel/aws/__init__.py#L145

For example:
```
failed_accont_ids = []
for account_id in account_ids:
    try:
        _sync_one_account(account_id)
    except Exception as e:
        logger.exception(e)
        failed_accont_ids.append(account_id)
if failed_accont_ids:
    raise Exception(f'Syncs failed for accounts {failed_accont_ids}')
```

**Comment by achantavy** [comment]
I agree on this approach and wanted to add that we should ensure that if there is an exception in one of the accounts, then execution stops and _does not_ continue on to the cleanup jobs. We cannot have an exception in the `get` phase cause all data to be deleted.

**Comment by achantavy** [comment]
@kunaals @ryan-lane @mpurusottamc - thoughts?

**Comment by ryan-lane** [comment]
Yes. This is a step in the direction I'd like to see. I'd really like to be able to run AWS accounts separately, and I think any work we'd need to make that work would also be needed for this.

**Comment by mpurusottamc** [comment]
Love the idea. This definitely avoids disruption in a multi-account setup.

+1 @achantavy for your idea of avoiding clean up in case of an exception in one of the accounts. We have been bitten on this in the past :)

**Comment by marco-lancini** [comment]
Hi all,
I'd like to revamp this discussion.

I'm currently trying to ingest a large-scale AWS Org, and it has been painful to get Cartography to complete even a single run.
With Orgs of this size, there is a high chance of facing resources with peculiar characteristics, which might ultimately led to a failed run. 

In my case, for the Org in question, just in the past week I had to open multiple issues (#800, #808, #809, #821) to add ad-hoc `try/catch` exceptions to multiple parts of the codebase, in order to get to a successful ingestion (and I'm not there yet, so more issues might come this way).

I understand the original idea of being conservative (especially for the cleanup jobs), 
but failing hard on a whole ingestion (oftentimes hours after it started) just because of an "odd" resource is becoming increasingly frustrating as a user.

Thoughts?

**Comment by ramonpetgrave64** [comment]
How do we feel about enabling this as an optional cli switch?

@achantavy I think it's okay to run the cleanup jobs, so long as all the cleanup jobs are account-specific. Most of them are, excpet for a few statements:
* https://github.com/lyft/cartography/blob/master/cartography/data/jobs/cleanup/aws_import_sqs_queues_cleanup.json#L9
* https://github.com/lyft/cartography/blob/master/cartography/data/jobs/cleanup/aws_import_elastic_ip_addresses_cleanup.json#L14-L19
* https://github.com/lyft/cartography/blob/master/cartography/data/jobs/cleanup/aws_import_ec2_key_pairs_cleanup.json#L8
* https://github.com/lyft/cartography/blob/master/cartography/data/jobs/cleanup/aws_import_tags_cleanup.json#L64
* https://github.com/lyft/cartography/blob/master/cartography/data/jobs/cleanup/aws_import_vpc_peering_cleanup.json#L33
* https://github.com/lyft/cartography/blob/master/cartography/data/jobs/cleanup/aws_post_ingestion_dns_cleanup.json#L1-L40

How do we feel about enabling this as an optional cli switch?

**Comment by marco-lancini** [comment]
> @marco-lancini How do we feel about enabling this as an optional cli switch?

Definitely a good idea for me. This would give flexibility to end users to choose the approach they prefer.

**Comment by ryan-lane** [comment]
Yeah, an optional CLI switch would be nice. That way we could chase down specific errors, while still having most of the data. As we add more support for more AWS services, the runs become slower and more likely to fail on something random, for some subset of people.

It would be ideal to catch the exception for each sub-module in aws, and if the flag is set, log the exception and keep going. It'll mean we'll be missing a subset of the data, but that's better than having all the data be stale.

**Comment by ryan-lane** [comment]
It's worth mentioning that with SyncMetadata, it's possible to determine if subsets of data are stale, so it's a bit less painful to let that happen :)
