### ISSUE TITLE
Issue installing on Apple M1

### ISSUE THREAD

**Issue by danielsaporo** [lyft/cartography#786]
I'm trying to install Cartography on a Mac that has an Apple M1 chip, and haven't had much luck. When I do:

```
pip3 install cartography
```

It fails with:

> Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects

Earlier in the output I see:

```
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/usr/local/opt/openssl@1.1/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c build/temp.macosx-10.14-arm64-3.8/_openssl.c -o build/temp.macosx-10.14-arm64-3.8/build/temp.macosx-10.14-arm64-3.8/_openssl.o -Wconversion -Wno-error=sign-conversion
      build/temp.macosx-10.14-arm64-3.8/_openssl.c:575:10: fatal error: 'openssl/opensslv.h' file not found
      #include <openssl/opensslv.h>
               ^~~~~~~~~~~~~~~~~~~~
      1 error generated.

```

Has anyone managed to get this running on a Mac with arm64 platform?

Note: I've already upgraded `pip` to the latest version.

**Comment by ramonpetgrave64** [comment]
I have not tried, but have you seen this? https://github.com/pyca/cryptography/issues/3489

**Comment by danielsaporo** [comment]
@ramonpetgrave64 yes, I also tried a lot of different things without any luck.

Thing is, if I do `pip3 install cryptography` (not cartography), it works.

I just don't know what it is with cryptography bundled with cartography that is making it fail like this.

**Comment by danielsaporo** [comment]
@ramonpetgrave64 I realised today that nothing I can try will get this working.

Cartography requires Neo4j 3.5, and there's no arm64 image for that.

So even if I were to solve the problem with cryptography, Apple M1 can't be supported before #521 is completed.

**Comment by ramonpetgrave64** [comment]
@danielsaporo I think you should still be able to install cartography without installing the neo4j database.

**Comment by danielsaporo** [comment]
@ramonpetgrave64 yes, a newer version of cryptography seems to work. Still, I won't be able to use Cartography without a more recent version of Neo4j.

**Comment by ramonpetgrave64** [comment]
@danielsaporo We are going to upgrade to Neo4j database 4.x. It's an effort we are planning to finish in the next couple months.

**Comment by ramonpetgrave64** [comment]
Neo4j now has some pre-release docker images for ARM. And I've verified with my team that they do work with Apple M1.
https://hub.docker.com/r/neo4j/neo4j-arm64-experimental/tags
