### ISSUE TITLE
Jira intel module

### ISSUE THREAD

**Issue by lfservin** [lyft/cartography#796]
**Feature request template**

*Title*: BSidesSF2019 refers to an intel module that access jira

*Description*:
> Sacha Faust described in detail around minute 25 of his talk how cartography integrates with jira. It is unfortunately not available. it would be great if it were, specially if it's already ready to use

[optional *Relevant Links*:]
Here's a [link](https://www.youtube.com/watch?v=ZukUmZSKSek) to the video in question

**Comment by ramonpetgrave64** [comment]
@lfservin Our internal Jira module is still very lyft-specific. Are there specific features or relationships that you would want in open source cartography?
