### ISSUE TITLE
"string indices must be integers" error

### ISSUE THREAD

**Issue by El070422** [lyft/cartography#801]
Hello everyone! Can you please help me with the issue? Cartography (0.53.0 and 0.54.0) successfully collected data for several aws accounts, everything worked fine. But data collection is not working for one of the accounts. We got the error:

ERROR:cartography.sync:Unhandled exception during sync stage 'aws'
Traceback (most recent call last):
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/sync.py", line 74, in run
    stage_func(neo4j_session, config)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/util.py", line 110, in timed
    return method(*args, **kwargs)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 208, in start_aws_ingestion
    _sync_multiple_accounts(
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 145, in _sync_multiple_accounts
    _sync_one_account(
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/intel/aws/__init__.py", line 57, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/util.py", line 110, in timed
    return method(*args, **kwargs)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/intel/aws/apigateway.py", line 376, in sync
    sync_apigateway_rest_apis(neo4j_session, boto3_session, region, current_aws_account_id, update_tag)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/util.py", line 110, in timed
    return method(*args, **kwargs)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/intel/aws/apigateway.py", line 366, in sync_apigateway_rest_apis
    load_rest_api_details(neo4j_session, stages_certificate_resources, current_aws_account_id, aws_update_tag)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/util.py", line 110, in timed
    return method(*args, **kwargs)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/intel/aws/apigateway.py", line 321, in load_rest_api_details
    _load_apigateway_certificates(neo4j_session, certificates, update_tag)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/util.py", line 110, in timed
    return method(*args, **kwargs)
  File "/home/centos/.local/lib/python3.8/site-packages/cartography/intel/aws/apigateway.py", line 243, in _load_apigateway_certificates
    certificate['createdDate'] = str(certificate['createdDate'])
TypeError: string indices must be integers

**Comment by ramonpetgrave64** [comment]
Can you help us debug this? https://lyft.github.io/cartography/dev/developer-guide.html
Can you try it again, but adding some debug log states, such as
```
logger.info(f'certificate {certificate}')
```

**Comment by kedarghule** [comment]
I took a quick look at the documentation. The attribute `createdDate` in certificate is of type datetime(). The code attempts to convert this to a string using str() so that the data can be ingested into Neo4j. 

Here's what I think the problem might be:
1) One way this can be done is using strftime() I guess
2) Another thing I'd like to point out is this comment by Alex - https://github.com/lyft/cartography/pull/633#discussion_r648882262

I'm not so sure about this and will look into it in a week (wrapping up my semester 🙈 )

**Comment by El070422** [comment]
Hi @kedarghule, I have tested strftime() and it seems to be working fine.

**Comment by El070422** [comment]
Hi,
I think the problem is in this part:


def _load_apigateway_certificates(
        neo4j_session: neo4j.Session, certificates: List, update_tag: int,
) -> None:
    """
    Ingest the API Gateway Client Certificate details into neo4j.
    """
    ingest_certificates = """
    UNWIND {certificates_list} as certificate
    MERGE (c:APIGatewayClientCertificate{id: certificate.clientCertificateId})
    ON CREATE SET c.firstseen = timestamp(), c.createddate = certificate.createdDate
    SET c.lastupdated = {UpdateTag}, c.expirationdate = certificate.expirationDate
    WITH c, certificate
    MATCH (stage:APIGatewayStage{id: certificate.stageArn})
    MERGE (stage)-[r:HAS_CERTIFICATE]->(c)
    ON CREATE SET r.firstseen = timestamp()
    SET r.lastupdated = {UpdateTag}
    """

    # neo4j does not accept datetime objects and values. This loop is used to convert
    # these values to string.
    for certificate in certificates:
        certificate['createdDate'] = str(certificate['createdDate'])
        certificate['expirationDate'] = str(certificate.get('expirationDate'))
        certificate['stageArn'] = "arn:aws:apigateway:::" + certificate['apiId'] + "/" + certificate['stageName']

bc you operate with certificates as with a list of  dictionaries, but when I run print(certificates) in your code I get the following list:
['ResponseMetadata', 'clientCertificateId', 'description', 'pemEncodedCertificate', 'createdDate', 'expirationDate', 'tags', 'stageName', 'apiId'],


and then error:
.....
File "/home/vagrant/cartography_debug/cartography/cartography/intel/aws/apigateway.py", line 245, in _load_apigateway_certificates
    **certificate['createdDate'] = str(certificate['createdDate'])
TypeError: string indices must be integers**

**Comment by El070422** [comment]
Hello @kedarghule,

Do you have any updates about the issue?

**Comment by kedarghule** [comment]
@El070422  I don't have a production environment to test this on. From your previous comment I see that only the keys are in the list but there is no corresponding value?

**Comment by El070422** [comment]
@kedarghule, yes only the keys as a list.

**Comment by kedarghule** [comment]
Okay. I see.
The part where the `certificates` list of dictionary is getting created is lines 308 to 310.
`if certificate:
            certificate['apiId'] = api_id
            certificates.extend(certificate)
`

Can you test it out here just to see what the output is? Thing is I don't have a production environment anymore and these resources so I can't test it out :/

**Comment by El070422** [comment]
Hi @kedarghule,

I'm sorry, my python lvl is helloworld. So I did the following:
if certificate:
            print("print certificate before apiid" + str(certificate))
            certificate['apiId'] = api_id
            print("********Print certificate['apiId'] " + str(certificate['apiId']))
            print("********Print certificate " + str(certificate))
            certificates.append(certificate)
            print("********Print certificates in the if " + str(certificates))
    print("*******Print certificates " + str(certificates))

output (I have changed part of the data):

INFO:cartography.intel.aws.apigateway:Syncing AWS APIGateway Rest APIs for region 'us-east-2' in account '158307blabla'.
print certificate before apiid{'ResponseMetadata': {'RequestId': '******-aa1e-4bd0-8d7g-c7d0215f9e32', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 24 May 2022 18:12:34 GMT', 'content-type': 'application/json', 'content-length': '1284', 'connection': 'keep-alive', 'x-amzn-requestid': '6d57db22-aa6e-4bd0-8d7f-c7d0225f9e32', 'x-amz-apigw-id': 'SpHy9LDtiKcEciA='}, 'RetryAttempts': 0}, 'clientCertificateId': 'jobbj1', 'description': 'cert for estimates', 'pemEncodedCertificate': '-----BEGIN CERTIFICATE-----\r\nMIIC6DCCAdCgAwIBAgIIcAH4CHX+DBEwDQYJKoZIhvcNAQELBQAwNDELMAkGA1UE\r\nBhMCVVMxEDAOBgNVBAcTB1NlYXR0bGUxEzARBgNVBAMTCkFwaUdhdGV3YXkwHhcN\r\nMTgwNzE0MDAyMjAyWhcNMTkwNzE0MDAyMjAyWjA0MQsw********0gArl3Q/qn2AxpqZ5yWU7lWmLhZLo/Z3bTDO6GHb7xkL\r\nTHL2cXsKS0WtmdOtEAAnCcSq3Th7tz19+3Yf9GCEu5DYcO8Y69Me6jOG/QpDF3EH\r\nMUhypsLQqkWChjUQYlmBaGCeMns59JowCnqbRi0FGXIMA0/D5/BJWr//Yu7l8PwM\r\nylSTOM0ory5jKVI3PF3mqJj5gokVfezMz2IMrIpdKKrzwYiHleBpAy8vyRLQkoRU\r\n6Ht22UX0lgOv7MPIt4OJY2NLjObUytb1m2s1hw==\r\n-----END CERTIFICATE-----', 'createdDate': datetime.datetime(2018, 7, 14, 0, 22, 2, tzinfo=tzlocal()), 'expirationDate': datetime.datetime(2019, 7, 14, 0, 22, 2, tzinfo=tzlocal()), 'tags': {}, 'stageName': 'beta'}
********Print certificate['apiId'] 1cx99rpaqb
********Print certificate {'ResponseMetadata': {'RequestId': '******-aa1e-4bd0-8d7f-c7d0215f9e32', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 24 May 2022 18:12:34 GMT', 'content-type': 'application/json', 'content-length': '1284', 'connection': 'keep-alive', 'x-amzn-requestid': '6d57db22-aa6e-4bd0-8d7f-c7d0215f9e32', 'x-amz-apigw-id': 'SpHy9LDtiYcEciA='}, 'RetryAttempts': 0}, 'clientCertificateId': 'jobbj1', 'description': 'cert for estimates', 'pemEncodedCertificate': '-----BEGIN CERTIFICATE-----\r\nMIIC6DCCAdCgAwIBAgIIcAH4CHX+DBEwDQYJKoZIhvcNAQELBQAwNDELMAkGA1UE\r\nBhMCVVMxEDAOBgNVBAcTB1NlYXR0bGUxEzARBgNVBAMTCkFwaUdhdGV3YXkwHhcN\r\nMTgwNzE0MDAyMjAyWhcNMTkwNzE0MDAyMjAyWjA0MQsw*********Br1uEdkmLL62fTnFvlnsMUxP8nquujJmGZUHuihcg\r\nWJctjR2IoNnKg/Np9cdC60j9+Vv/kYl3FKhMdcQFPuhQ/Z8CAwEAATANBgkqhkiG\r\n9w0BAQsFAAOCAQEANxtdbLsIZtRCnIiflSVKjLfn3dT/tvmXyODnKfwsSPgIpbO5\r\ncokdLz0gMG+Xfg1+p3Y60gArl3Q/qn2AxpqZ5yWU7lWmLhZLo/Z3bTDO6GHb7xkL\r\nTHL2cXsKS0WtmdOtEAAnCcSq3Th7tz19+3Yf9GCEu5DYcO8Y69Me6jOG/QpDF3EH\r\nMUhypsLQqkWCj1UQYlmBaGCeMns59JowCnqbRi0FGXIMA0/D5/BJWr//Yu7l8PwM\r\nylSTOM0ory5jKVI3PF3mqJj5gokVfezMz2IMrIpdKKrzwYiHleBpAy8vyRLQkoRU\r\n6Ht22UX0lgOv7MPIt4OJY2NLjObUytb1m2s1hw==\r\n-----END CERTIFICATE-----', 'createdDate': datetime.datetime(2018, 7, 14, 0, 22, 2, tzinfo=tzlocal()), 'expirationDate': datetime.datetime(2019, 7, 14, 0, 22, 2, tzinfo=tzlocal()), 'tags': {}, 'stageName': 'beta', 'apiId': '1cx99rpaqb'}
********Print certificates in the if ['ResponseMetadata', 'clientCertificateId', 'description', 'pemEncodedCertificate', 'createdDate', 'expirationDate', 'tags', 'stageName', 'apiId']
*******Print certificates ['ResponseMetadata', 'clientCertificateId', 'description', 'pemEncodedCertificate', 'createdDate', 'expirationDate', 'tags', 'stageName', 'apiId']

Looks like **certificates.extend(certificate)** adds only keys to a list. Can we use append? I tried to replace extend method and it worked without errors.

**Comment by El070422** [comment]
Hello @kedarghule,

Do you have any updates about the issue?

**Comment by kedarghule** [comment]
> Hello @kedarghule,
> 
> Do you have any updates about the issue?

I think using append may work although extend is faster and hence I used it. Can be a quick fix. Would you want to open a PR for the fix?

cc: @mpurusottamc can also take a look?

**Comment by mpurusottamc** [comment]
> I think using append may work although extend is faster and hence I used it. Can be a quick fix. Would you want to open a PR for the fix?

@El070422 `extend` is useful when you are inserting multiple list items (dictionary or otherwise) to an existing list. If you use `extend` to add a Dictionary to a List, it always adds the keys. Hence this issue. It could have been an oversight :(.

We should use `append` in the case, since we are adding a dictionary (`certificate`) into the `certificates` list.

cc: @kedarghule
