### ISSUE TITLE
Cartography Installation Error

### ISSUE THREAD

**Issue by akashchavan03** [lyft/cartography#807]
*Title*: *Unable to setup cartography for AWS account*

Hello everyone! can you help with the issue? I'm trying to setup cartography for single AWS account.

*Description*:
I'm following installation documentation. I have setup a local VM running Ubuntu. Installed and configured AWS CLI on it. As document described installed neo4j 3.5 community server. Its running fine on localhost:7687. Then I installed cartography by running "pip install cartography" command in terminal. its installed but next step aws sync is not working. Can anyone guide me how to perform sync. when I run "cartography --bolt://localhost:7687" command it says cartography command not found. same happen when I use "cartography --help" command. I'll appreciate if someone help me out with installation.

*Basic Information*:
OS: Ubuntu 20.04.4 LTS (x64) running on vmware
Python: Python 3 (3.8.10) 
Cartography Release: 0.55.0

Attaching installation logs of cartography pip package. I have seen some errors during installation attaching screenshot to highlight them.

*Installation Log*:

akash@ubuntu:~$ pip install cartography
Collecting cartography
  Downloading cartography-0.55.0-py3-none-any.whl (296 kB)
     |████████████████████████████████| 296 kB 6.8 MB/s 
Collecting azure-mgmt-cosmosdb>=6.0.0
  Downloading azure_mgmt_cosmosdb-6.4.0-py2.py3-none-any.whl (290 kB)
     |████████████████████████████████| 290 kB 11.3 MB/s 
Collecting statsd
  Downloading statsd-3.3.0-py2.py3-none-any.whl (11 kB)
Collecting python-digitalocean>=1.16.0
  Downloading python_digitalocean-1.17.0-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 6.7 MB/s 
Collecting dnspython>=1.15.0
  Downloading dnspython-2.2.1-py3-none-any.whl (269 kB)
     |████████████████████████████████| 269 kB 11.7 MB/s 
Collecting neo4j<4.0.0,>=1.7.6
  Downloading neo4j-1.7.6.tar.gz (23 kB)
Collecting azure-mgmt-storage>=16.0.0
  Downloading azure_mgmt_storage-20.0.0-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 12.8 MB/s 
Collecting policyuniverse>=1.1.0.0
  Downloading policyuniverse-1.4.0.20220110-py2.py3-none-any.whl (349 kB)
     |████████████████████████████████| 349 kB 4.4 MB/s 
Collecting boto3>=1.15.1
  Downloading boto3-1.21.37-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 7.2 MB/s 
Collecting kubernetes<=21.7.0,>=18.20.0
  Downloading kubernetes-21.7.0-py2.py3-none-any.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 5.9 MB/s 
Collecting pdpyras>=4.3.0
  Downloading pdpyras-4.5.0.tar.gz (28 kB)
Requirement already satisfied: requests>=2.22.0 in /usr/lib/python3/dist-packages (from cartography) (2.22.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/lib/python3/dist-packages (from cartography) (5.3.1)
Collecting marshmallow>=3.0.0rc7
  Downloading marshmallow-3.15.0-py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 3.7 MB/s 
Collecting azure-cli-core>=2.26.0
  Downloading azure_cli_core-2.35.0-py3-none-any.whl (180 kB)
     |████████████████████████████████| 180 kB 4.7 MB/s 
Collecting botocore>=1.18.1
  Downloading botocore-1.24.37-py3-none-any.whl (8.7 MB)
     |████████████████████████████████| 8.7 MB 3.4 MB/s 
Collecting okta<1.0.0
  Downloading okta-0.0.4.tar.gz (15 kB)
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 4.6 MB/s 
Collecting oauth2client>=4.1.3
  Downloading oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 4.1 MB/s 
Collecting azure-identity>=1.5.0
  Downloading azure_identity-1.9.0-py3-none-any.whl (134 kB)
     |████████████████████████████████| 134 kB 6.1 MB/s 
Collecting msrestazure>=0.6.4
  Downloading msrestazure-0.6.4-py2.py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 5.3 MB/s 
Collecting cryptography<3.4,>=3.2
  Downloading cryptography-3.3.2-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB 7.3 MB/s 
Collecting azure-mgmt-resource>=10.2.0
  Downloading azure_mgmt_resource-21.0.0-py3-none-any.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 4.1 MB/s 
Collecting adal>=1.2.4
  Downloading adal-1.2.7-py2.py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 3.0 MB/s 
Collecting azure-mgmt-sql<=1.0.0
  Downloading azure_mgmt_sql-1.0.0-py2.py3-none-any.whl (711 kB)
     |████████████████████████████████| 711 kB 5.3 MB/s 
Collecting azure-mgmt-compute>=5.0.0
  Downloading azure_mgmt_compute-26.1.0-py3-none-any.whl (4.8 MB)
     |████████████████████████████████| 4.8 MB 4.0 MB/s 
Collecting google-api-python-client>=1.7.8
  Downloading google_api_python_client-2.43.0-py2.py3-none-any.whl (8.3 MB)
     |████████████████████████████████| 8.3 MB 754 kB/s 
Collecting neobolt<4.0.0,>=1.7.0
  Downloading neobolt-1.7.17.tar.gz (183 kB)
     |████████████████████████████████| 183 kB 9.5 MB/s 
Collecting azure-common~=1.1
  Downloading azure_common-1.1.28-py2.py3-none-any.whl (14 kB)
Collecting msrest>=0.6.21
  Downloading msrest-0.6.21-py2.py3-none-any.whl (85 kB)
     |████████████████████████████████| 85 kB 5.4 MB/s 
Collecting azure-mgmt-core<2.0.0,>=1.2.0
  Downloading azure_mgmt_core-1.3.0-py2.py3-none-any.whl (25 kB)
Collecting jsonpickle
  Downloading jsonpickle-2.1.0-py2.py3-none-any.whl (38 kB)
Collecting neotime~=1.7.1
  Downloading neotime-1.7.4.tar.gz (17 kB)
Collecting jmespath<2.0.0,>=0.7.1
  Downloading jmespath-1.0.0-py3-none-any.whl (23 kB)
Collecting s3transfer<0.6.0,>=0.5.0
  Downloading s3transfer-0.5.2-py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 7.0 MB/s 
Requirement already satisfied: urllib3>=1.24.2 in /usr/lib/python3/dist-packages (from kubernetes<=21.7.0,>=18.20.0->cartography) (1.25.8)
Collecting websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0
  Downloading websocket_client-1.3.2-py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 4.4 MB/s 
Requirement already satisfied: certifi>=14.05.14 in /usr/lib/python3/dist-packages (from kubernetes<=21.7.0,>=18.20.0->cartography) (2019.11.28)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/lib/python3/dist-packages (from kubernetes<=21.7.0,>=18.20.0->cartography) (2.7.3)
Requirement already satisfied: setuptools>=21.0.0 in /usr/lib/python3/dist-packages (from kubernetes<=21.7.0,>=18.20.0->cartography) (45.2.0)
Collecting google-auth>=1.0.1
  Downloading google_auth-2.6.3-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 11.4 MB/s 
Collecting requests-oauthlib
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from kubernetes<=21.7.0,>=18.20.0->cartography) (1.14.0)
Collecting psutil~=5.9; sys_platform != "cygwin"
  Downloading psutil-5.9.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (283 kB)
     |████████████████████████████████| 283 kB 5.7 MB/s 
Collecting azure-cli-telemetry==1.0.6.*
  Downloading azure_cli_telemetry-1.0.6-py3-none-any.whl (10 kB)
Collecting argcomplete~=1.8
  Downloading argcomplete-1.12.3-py2.py3-none-any.whl (38 kB)
Collecting knack~=0.9.0
  Downloading knack-0.9.0-py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 6.6 MB/s 
Collecting paramiko<3.0.0,>=2.0.8
  Downloading paramiko-2.10.3-py2.py3-none-any.whl (211 kB)
     |████████████████████████████████| 211 kB 11.6 MB/s 
Collecting pyopenssl>=17.1.0
  Downloading pyOpenSSL-22.0.0-py2.py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 5.3 MB/s 
Collecting PyJWT>=2.1.0
  Downloading PyJWT-2.3.0-py3-none-any.whl (16 kB)
Collecting pkginfo>=1.5.0.1
  Downloading pkginfo-1.8.2-py2.py3-none-any.whl (26 kB)
Collecting msal-extensions<0.4,>=0.3.1
  Downloading msal_extensions-0.3.1-py2.py3-none-any.whl (18 kB)
Collecting msal<2.0.0,>=1.17.0
  Downloading msal-1.17.0-py2.py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 5.6 MB/s 
Collecting humanfriendly~=10.0
  Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
     |████████████████████████████████| 86 kB 2.8 MB/s 
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.8-py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 8.0 MB/s 
Collecting pyasn1-modules>=0.0.5
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 4.2 MB/s 
Collecting rsa>=3.1.4
  Downloading rsa-4.8-py3-none-any.whl (39 kB)
Requirement already satisfied: httplib2>=0.9.1 in /usr/lib/python3/dist-packages (from oauth2client>=4.1.3->cartography) (0.14.0)
Collecting pyasn1>=0.1.7
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 7.1 MB/s 
Collecting azure-core<2.0.0,>=1.11.0
  Downloading azure_core-1.23.1-py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 10.4 MB/s 
Collecting cffi>=1.12
  Downloading cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
     |████████████████████████████████| 446 kB 11.5 MB/s 
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
  Downloading google_api_core-2.7.1-py3-none-any.whl (114 kB)
     |████████████████████████████████| 114 kB 11.9 MB/s 
Collecting google-auth-httplib2>=0.1.0
  Downloading google_auth_httplib2-0.1.0-py2.py3-none-any.whl (9.3 kB)
Collecting uritemplate<5,>=3.0.1
  Downloading uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)
Collecting isodate>=0.6.0
  Downloading isodate-0.6.1-py2.py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 1.0 MB/s 
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from neotime~=1.7.1->neo4j<4.0.0,>=1.7.6->cartography) (2019.3)
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.0.0-py3-none-any.whl (9.1 kB)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib->kubernetes<=21.7.0,>=18.20.0->cartography) (3.1.0)
Collecting applicationinsights<0.12,>=0.11.1
  Downloading applicationinsights-0.11.10-py2.py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 3.4 MB/s 
Collecting portalocker~=1.2
  Downloading portalocker-1.7.1-py2.py3-none-any.whl (10 kB)
Collecting pygments
  Downloading Pygments-2.11.2-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 11.7 MB/s 
Collecting tabulate
  Downloading tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting bcrypt>=3.1.3
  Downloading bcrypt-3.2.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (61 kB)
     |████████████████████████████████| 61 kB 1.0 MB/s 
Requirement already satisfied: pynacl>=1.0.1 in /usr/lib/python3/dist-packages (from paramiko<3.0.0,>=2.0.8->azure-cli-core>=2.26.0->cartography) (1.3.0)
Collecting typing-extensions>=4.0.1
  Downloading typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB 6.4 MB/s 
Collecting protobuf>=3.12.0
  Downloading protobuf-3.20.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 6.2 MB/s 
Collecting googleapis-common-protos<2.0dev,>=1.52.0
  Downloading googleapis_common_protos-1.56.0-py2.py3-none-any.whl (241 kB)
     |████████████████████████████████| 241 kB 4.8 MB/s 
Building wheels for collected packages: neo4j, pdpyras, okta, neobolt, neotime
  Building wheel for neo4j (setup.py) ... done
  Created wheel for neo4j: filename=neo4j-1.7.6-py3-none-any.whl size=32570 sha256=592904f7474bbfc80db0a370b04e5ac3b62f75f8f6ac278f8551d2e638ad8c37
  Stored in directory: /home/akash/.cache/pip/wheels/dd/6e/82/d08530f1168e3af67cab9f454d8816b7e4fec09ae4f5ce0c12
  Building wheel for pdpyras (setup.py) ... done
  Created wheel for pdpyras: filename=pdpyras-4.5.0-py3-none-any.whl size=17808 sha256=be6006a12e32a896182e9cdffc040722c3f7aa085aaf49a6c182f452f88204dd
  Stored in directory: /home/akash/.cache/pip/wheels/0d/1b/bc/b080264d9a968c62df8b38d6fa6e446ce9c1f0fb6cb8374faf
  Building wheel for okta (setup.py) ... done
  Created wheel for okta: filename=okta-0.0.4-py2.py3-none-any.whl size=35348 sha256=a16dedb0f45a5886b90dc4d61e879444f5257d030757a73d8d1e043d9c44daf9
  Stored in directory: /home/akash/.cache/pip/wheels/9b/23/ea/7ac274c5a7abba0c3228774681e032cc91cdf85c109602c957
  Building wheel for neobolt (setup.py) ... done
  Created wheel for neobolt: filename=neobolt-1.7.17-cp38-cp38-linux_x86_64.whl size=805973 sha256=3f10e9765e6c3d376cc4a960a45752c9d771b36316fd66f977390a9cb324c1cb
  Stored in directory: /home/akash/.cache/pip/wheels/a0/73/f2/5311198d8b3a2df813d3bc31e6af3418069cd9e461b91e21ee
  Building wheel for neotime (setup.py) ... done
  Created wheel for neotime: filename=neotime-1.7.4-py3-none-any.whl size=20541 sha256=420ba910f3c882adeb107b2bd4e560ae441a5a7ebccbb6d931b67a0594c47de1
  Stored in directory: /home/akash/.cache/pip/wheels/84/2d/01/a397b73c9e48f6c44342c06c436b20b44d53a71f6ba972a992
Successfully built neo4j pdpyras okta neobolt neotime
ERROR: kubernetes 21.7.0 has requirement pyyaml>=5.4.1, but you'll have pyyaml 5.3.1 which is incompatible.
ERROR: pyopenssl 22.0.0 has requirement cryptography>=35.0, but you'll have cryptography 3.3.2 which is incompatible.
ERROR: google-auth-httplib2 0.1.0 has requirement httplib2>=0.15.0, but you'll have httplib2 0.14.0 which is incompatible.
ERROR: google-api-python-client 2.43.0 has requirement httplib2<1dev,>=0.15.0, but you'll have httplib2 0.14.0 which is incompatible.
Installing collected packages: azure-common, requests-oauthlib, isodate, msrest, typing-extensions, azure-core, azure-mgmt-core, azure-mgmt-cosmosdb, statsd, jsonpickle, python-digitalocean, dnspython, neobolt, neotime, neo4j, azure-mgmt-storage, policyuniverse, jmespath, botocore, s3transfer, boto3, websocket-client, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, kubernetes, pdpyras, pyparsing, packaging, marshmallow, psutil, applicationinsights, portalocker, azure-cli-telemetry, argcomplete, pygments, tabulate, knack, pycparser, cffi, bcrypt, cryptography, paramiko, pyopenssl, PyJWT, pkginfo, msal, msal-extensions, adal, msrestazure, humanfriendly, azure-cli-core, okta, oauth2client, azure-identity, azure-mgmt-resource, azure-mgmt-sql, azure-mgmt-compute, protobuf, googleapis-common-protos, google-api-core, google-auth-httplib2, uritemplate, google-api-python-client, cartography
  WARNING: The script wsdump is installed in '/home/akash/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts pyrsa-decrypt, pyrsa-encrypt, pyrsa-keygen, pyrsa-priv2pub, pyrsa-sign and pyrsa-verify are installed in '/home/akash/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pygmentize is installed in '/home/akash/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tabulate is installed in '/home/akash/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pkginfo is installed in '/home/akash/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script humanfriendly is installed in '/home/akash/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts cartography and cartography-detectdrift are installed in '/home/akash/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed PyJWT-2.3.0 adal-1.2.7 applicationinsights-0.11.10 argcomplete-1.12.3 azure-cli-core-2.35.0 azure-cli-telemetry-1.0.6 azure-common-1.1.28 azure-core-1.23.1 azure-identity-1.9.0 azure-mgmt-compute-26.1.0 azure-mgmt-core-1.3.0 azure-mgmt-cosmosdb-6.4.0 azure-mgmt-resource-21.0.0 azure-mgmt-sql-1.0.0 azure-mgmt-storage-20.0.0 bcrypt-3.2.0 boto3-1.21.37 botocore-1.24.37 cachetools-5.0.0 cartography-0.55.0 cffi-1.15.0 cryptography-3.3.2 dnspython-2.2.1 google-api-core-2.7.1 google-api-python-client-2.43.0 google-auth-2.6.3 google-auth-httplib2-0.1.0 googleapis-common-protos-1.56.0 humanfriendly-10.0 isodate-0.6.1 jmespath-1.0.0 jsonpickle-2.1.0 knack-0.9.0 kubernetes-21.7.0 marshmallow-3.15.0 msal-1.17.0 msal-extensions-0.3.1 msrest-0.6.21 msrestazure-0.6.4 neo4j-1.7.6 neobolt-1.7.17 neotime-1.7.4 oauth2client-4.1.3 okta-0.0.4 packaging-21.3 paramiko-2.10.3 pdpyras-4.5.0 pkginfo-1.8.2 policyuniverse-1.4.0.20220110 portalocker-1.7.1 protobuf-3.20.0 psutil-5.9.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.21 pygments-2.11.2 pyopenssl-22.0.0 pyparsing-3.0.8 python-digitalocean-1.17.0 requests-oauthlib-1.3.1 rsa-4.8 s3transfer-0.5.2 statsd-3.3.0 tabulate-0.8.9 typing-extensions-4.1.1 uritemplate-4.1.1 websocket-client-1.3.2
akash@ubuntu:~$ 

![sync error](https://user-images.githubusercontent.com/63378733/162999649-e5abd771-d4af-4144-9d08-21266f1bd6d4.PNG)
![Installation error](https://user-images.githubusercontent.com/63378733/162999697-f056e3d8-207f-49cd-b3ba-13eba4ea8222.PNG)

**Comment by ramonpetgrave64** [comment]
Check the Warnings in your output. It seems like for your particular Ubuntu setup, your python modules are not being added to your PATH.
