### ISSUE TITLE
RFC: lyft/Cartography, Neo4J 4.x, Monkeypatching

### ISSUE THREAD

**Issue by ramonpetgrave64** [lyft/cartography#838]
*RFC: lyft/Cartography, Neo4J 4.x, Monkeypatching*
We're doing some automatic query syntax/code changes to help us migrate from Neo4j 3.5 to 4.x. Comments welcome!
https://docs.google.com/document/d/1DR-XPzEpd5o_aqvgH28mdIJG-2WSeektx2V9hETFXuM/edit#heading=h.cqtqxkjjli6n

Update Ju ne 21, 2022

The auto-patcher has been released in #861, with special developer instructions. Pre-releases  with the patch enabled by default can be had from releases tagged like `0.62.0.dev1`.

**Comment by achantavy** [comment]
Closing this out as we have fully implemented this.
