### ISSUE TITLE
Where can I find the config file of cartography?

### ISSUE THREAD

**Issue by steve-solun** [lyft/cartography#894]
I am scanning my aws and trying to config which resources to map, which regions etc.
Where can I find the option to filter what to scan?

@achantavy

**Comment by achantavy** [comment]
It's documented in `cartography -h`:

```
  --aws-requested-syncs AWS_REQUESTED_SYNCS
                        Comma-separated list of AWS resources to sync. Example 1: "ecr,s3,ec2:instance" for ECR, S3, and all EC2 instance resources. See
                        the full list available in source code at cartography.intel.aws.resources. If not specified, cartography by default will run all
                        AWS sync modules available.
```

Source: https://github.com/lyft/cartography/blob/3fa62ee2c07b92954ef5a4f4d039d4c94e918e85/cartography/cli.py#L188-L196

cartography.intel.aws.resources: https://github.com/lyft/cartography/blob/3fa62ee2c07b92954ef5a4f4d039d4c94e918e85/cartography/intel/aws/resources.py#L44

**Comment by steve-solun** [comment]
Great @achantavy thanks a lot!
And if I want to scan it on daily/hourly basis where can I configure such job?
Will it override/conflict with existing ids?
Thanks in advance!

**Comment by achantavy** [comment]
You can configure one or more cronjobs for that. As long as the same resources aren't being synced at the same time by parallel crons then I don't think you'll have problems. That said, parallel cron management is difficult already. I'd recommend starting with keeping it simple, evaluating later on how frequent your users need the data, and then adjusting.

Here are some ideas regarding deploying cartography in prod:

- Ops tips like how we keep data up to date and observability: https://lyft.github.io/cartography/ops.html
- You can write custom sync commands to arrange your crons: https://lyft.github.io/cartography/dev/developer-guide.html?highlight=custom%20sync#implementing-custom-sync-commands
- You can also write your own intel module plugin by following these steps: https://lyft.github.io/cartography/dev/writing-intel-modules.html. We'd also happily welcome PRs here too.
- A few blogs for ideas: [Mapping moving clouds](https://blog.marcolancini.it/2020/blog-tracking-moving-clouds-with-cartography/), [Tracking moving clouds](https://blog.marcolancini.it/2020/blog-tracking-moving-clouds-with-cartography/), [IAM whatever you say IAM](https://eng.lyft.com/iam-whatever-you-say-iam-febce59d1e3b).

**Comment by steve-solun** [comment]
Thanks a lot @achantavy
