### ISSUE TITLE
AWS Inspector findings timeout

### ISSUE THREAD

**Issue by at4z** [lyft/cartography#988]
*Title*: *AWS Inspector findings timeout*

*Description*:
> Cartography is crashing when attempting to retrieve Inspector finding from ap-northeast-3

*To Reproduce*:
> cartography --experimental-neo4j-4x-support --neo4j-uri bolt://127.0.0.1:7687  --aws-sync-all-profiles

*Logs*:
> INFO:cartography.intel.aws.inspector:Syncing AWS Inspector findings for account XXX and region ap-northeast-3
INFO:backoff:Backing off inner_function(...) for 1.0s (botocore.exceptions.ClientError: An error occurred (InternalServerErrorException) when calling the ListFindings operation (reached max retries: 4): Endpoint request timed out)
WARNING:cartography.util:Backing off 1.0 seconds after 1 tries. Calling function <function aws_handle_regions.<locals>.inner_function at 0x106b0e710>
INFO:backoff:Backing off inner_function(...) for 0.2s (botocore.exceptions.ClientError: An error occurred (InternalServerErrorException) when calling the ListFindings operation (reached max retries: 4): Endpoint request timed out)
WARNING:cartography.util:Backing off 0.2 seconds after 2 tries. Calling function <function aws_handle_regions.<locals>.inner_function at 0x106b0e710>
INFO:backoff:Backing off inner_function(...) for 0.2s (botocore.exceptions.ClientError: An error occurred (InternalServerErrorException) when calling the ListFindings operation (reached max retries: 4): Endpoint request timed out)
WARNING:cartography.util:Backing off 0.2 seconds after 3 tries. Calling function <function aws_handle_regions.<locals>.inner_function at 0x106b0e710>
INFO:backoff:Backing off inner_function(...) for 6.4s (botocore.exceptions.ClientError: An error occurred (InternalServerErrorException) when calling the ListFindings operation (reached max retries: 4): Endpoint request timed out)
WARNING:cartography.util:Backing off 6.4 seconds after 4 tries. Calling function <function aws_handle_regions.<locals>.inner_function at 0x106b0e710>
ERROR:backoff:Giving up inner_function(...) after 5 tries (botocore.exceptions.ClientError: An error occurred (InternalServerErrorException) when calling the ListFindings operation (reached max retries: 4): Endpoint request timed out)

*Please complete the following information:*:
>  - Cartography 0.65.0

*Additional context*:
> Sounds like inspector does not exist in ap-northeast-3, so maybe that has something to do with it?

**Comment by ramonpetgrave64** [comment]
We're having some problems with this sync module internally. The regular `SecurityAudit` managed policy seems to still not have permissions for `inspector2`, only for `inspector`.

Try adding the `AmazonInspector2ReadOnlyAccess` managed policy to your role or user that cartography uses.

**Comment by ramonpetgrave64** [comment]
It seems like inspector is not available in ap-northeast-3. I'm trying a workaround.
