### ISSUE TITLE
Proposal for improvements to `exposed_internet` on Load Balancers

### ISSUE THREAD

**Issue by scriptsrc** [lyft/cartography#99]
Hey Lyft team,

This tool is pretty neat. Thank you for building and sharing it.

Right now loadbalancers and any attached instances are flagged with `exposed_internet` if the scheme on the loadbalancer is `internet-facing`.

I believe this creates a number of false positives. My proposal is to change the logic to only flag loadbalancers and instances when the following criteria are met:

1. Loadbalancer has an internet-facing scheme. (public DNS)
2. Loadbalancer has a listener on the same protocol and port as one of the security group rules allowing `0.0.0.0/0`.  (Care must be taken for rules with "any" protocol or port ranges.)

It seems like this kind of logic should be pretty easy with a graph database, but I'm very new to neo4j.  (I have been trying to come up with a query that performs something like this and outputs a list of dns entries and ports that should be internet-reachable. I would *love* any help if such a query is possible)

This is the same logic I used when I wrote the Security Monkey auditor for load balancers:
ELBs: https://github.com/Netflix/security_monkey/blob/develop/security_monkey/auditors/elb.py#L182
ALBs: https://github.com/Netflix/security_monkey/blob/develop/security_monkey/auditors/elbv2.py#L63

Please let me know what you think of this proposal.  If there are reasons why you are not already looking at the listeners/sg's, I would love to learn what those are.

Thank you.  Great tool!

**Comment by scriptsrc** [comment]
I started the pluralsight course on neo4j and was able to come up with a query for this:

To get a table: (has some duplicates that I don't know how to get rid of yet)
```
MATCH (cidr:IpRange)—->(perm:IpPermissionInbound)—->(sg:EC2SecurityGroup)<-—(elb:LoadBalancer)—->(listener:ELBListener)
WHERE elb.scheme = "internet-facing" AND cidr.range = "0.0.0.0/0" AND listener.port<=perm.fromport AND listener.port<=perm.toport
RETURN elb.dnsname, listener.port
```

To see a visualization:
```
MATCH (cidr:IpRange)—->(perm:IpPermissionInbound)—->(sg:EC2SecurityGroup)<-—(elb:LoadBalancer)—->(listener:ELBListener)
WHERE elb.scheme = "internet-facing" AND cidr.range = "0.0.0.0/0" AND listener.port<=perm.fromport AND listener.port<=perm.toport
RETURN elb, listener, sg, perm, cidr
```

These could fail if the IpPermissionInbound uses `-1` for protocol, but otherwise I think they're decent.

**Comment by sachafaust** [comment]
@scriptsrc Thank you for the suggestion and you are a quick learner. I implemented the suggestion as part of our analysis job. See PR https://github.com/lyft/cartography/pull/100

**Comment by scriptsrc** [comment]
It's that easy to update??  wow.  I wonder if we need to worry about SG's with an `any` protocol as the `fromport` and `toport` might be `-1`.  I'll try to look into this.

**Is there a roadmap published for Cartograpy?** I'm curious about what technologies are next and I'd love to learn how to model attacks with the tool if anyone is doing that.

My thoughts on what should come next:
- ALBs, maybe even NLBs
- rdsdbclusters (Aurora) and/or redshift

**Comment by achantavy** [comment]
#100 has been merged, thanks for your contribution!  As far as roadmap goes, let's ping @sachafaust again :)
